In [2]:
from hotel import final_hotel_data_processor
from room  import load_room_data
# 함수 사용
hotel= final_hotel_data_processor()
room= load_room_data()
# 필요라이브러리 로딩
import pymysql
import pandas as pd
import numpy as np
import seaborn as sns  # 시각화 라이브러리, matplotlib보다 단순함
import matplotlib.pyplot as plt
import plotly.io as pio
import plotly.express as px 
plt.rcParams['font.family'] = 'Malgun Gothic'
import warnings
warnings.filterwarnings('ignore')
pd.options.display.float_format = '{:.0f}'.format
pd.set_option('display.max_rows', 200)
import pandas as pd 
import chardet

# 1데이터로드

In [1]:
import os
new_directory = "./2024_가격예측모델"

# 현재 디렉토리 변경
os.chdir(new_directory)

In [3]:
os.getcwd()

'C:\\Users\\user\\Work\\2024_가격예측모델'

In [4]:
# 샘플데이터로드 
df=pd.read_csv('./raw_data/hotel_price_price_raw_2201_2402.csv')
df

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,region,room_name,hotel_name,hoteLgrade,객실수,업태구분명
0,1535,-64055505,2022-01-02,2022-01-01 11:00:00,1,53476,0 days 13:00:00,2022-01-01,AGODA,경상,Double Room,창원명서동시카고,미등급,미분류,미분류
1,1535,-64055505,2022-01-03,2022-01-01 11:00:00,1,53476,1 days 13:00:00,2022-01-01,AGODA,경상,Double Room,창원명서동시카고,미등급,미분류,미분류
2,1535,-64055505,2022-01-03,2022-01-02 11:00:00,1,53476,0 days 13:00:00,2022-01-02,AGODA,경상,Double Room,창원명서동시카고,미등급,미분류,미분류
3,1535,-64055505,2022-01-03,2022-01-02 23:00:00,1,53476,0 days 01:00:00,2022-01-02,AGODA,경상,Double Room,창원명서동시카고,미등급,미분류,미분류
4,1535,-64055505,2022-01-04,2022-01-01 11:00:00,1,53476,2 days 13:00:00,2022-01-01,AGODA,경상,Double Room,창원명서동시카고,미등급,미분류,미분류
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48084997,1652,117069351,2023-05-03,2023-04-16 23:00:00,1,73326,16 days 01:00:00,2023-04-16,AGODA,제주,Small Room,중문리조트,1성,44,가족호텔_제주
48084998,1652,117069351,2023-05-05,2023-04-16 23:00:00,1,85216,18 days 01:00:00,2023-04-16,AGODA,제주,Small Room,중문리조트,1성,44,가족호텔_제주
48084999,1652,186053192,2023-09-01,2023-08-05 00:00:00,1,83070,27 days 00:00:00,2023-08-05,AGODA,제주,스몰룸 (Small Room),중문리조트,1성,44,가족호텔_제주
48085000,1652,186053192,2023-09-01,2023-08-05 11:00:00,0,83070,26 days 13:00:00,2023-08-05,AGODA,제주,스몰룸 (Small Room),중문리조트,1성,44,가족호텔_제주
48085001,1652,186053192,2023-09-01,2023-08-05 23:00:00,0,83070,26 days 01:00:00,2023-08-05,AGODA,제주,스몰룸 (Small Room),중문리조트,1성,44,가족호텔_제주

In [5]:
# 범위 축소를 위해 3성만 필터 
df=df.query('hoteLgrade=="3성"')
df

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,region,room_name,hotel_name,hoteLgrade,객실수,업태구분명
6918662,250,-10671338,2022-01-01,2022-01-01 11:00:00,1,235646,-1 days +13:00:00,2022-01-01,AGODA,부산,Deluxe Twin Room,호메르스호텔,3성,143,관광호텔업
6918663,250,-10671338,2022-01-01,2022-01-01 23:00:00,1,235646,-1 days +01:00:00,2022-01-01,AGODA,부산,Deluxe Twin Room,호메르스호텔,3성,143,관광호텔업
6918664,250,-10671338,2022-01-08,2022-01-01 01:00:00,1,226806,6 days 23:00:00,2022-01-01,AGODA,부산,Deluxe Twin Room,호메르스호텔,3성,143,관광호텔업
6918665,250,-10671338,2022-01-08,2022-01-01 03:00:00,1,227521,6 days 21:00:00,2022-01-01,AGODA,부산,Deluxe Twin Room,호메르스호텔,3성,143,관광호텔업
6918666,250,-10671338,2022-01-08,2022-01-01 23:00:00,1,227521,6 days 01:00:00,2022-01-01,AGODA,부산,Deluxe Twin Room,호메르스호텔,3성,143,관광호텔업
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36963657,217,282203325,2024-02-25,2024-02-10 23:00:00,1,64925,14 days 01:00:00,2024-02-10,GOODCHOICE,울산,[LUCKY NEW YEAR] 디럭스 트윈,신라스테이울산,3성,335,관광호텔업
36963658,217,282203325,2024-02-25,2024-02-12 00:00:00,1,67925,13 days 00:00:00,2024-02-12,GOODCHOICE,울산,[LUCKY NEW YEAR] 디럭스 트윈,신라스테이울산,3성,335,관광호텔업
36963659,217,282203325,2024-02-25,2024-02-12 23:00:00,1,67925,12 days 01:00:00,2024-02-12,GOODCHOICE,울산,[LUCKY NEW YEAR] 디럭스 트윈,신라스테이울산,3성,335,관광호텔업
36963660,217,282203325,2024-02-25,2024-02-14 01:00:00,1,64925,10 days 23:00:00,2024-02-14,GOODCHOICE,울산,[LUCKY NEW YEAR] 디럭스 트윈,신라스테이울산,3성,335,관광호텔업
36963661,217,282203325,2024-02-25,2024-02-14 23:00:00,1,64925,10 days 01:00:00,2024-02-14,GOODCHOICE,울산,[LUCKY NEW YEAR] 디럭스 트윈,신라스테이울산,3성,335,관광호텔업

In [5]:
# 범위 축소 2 일단 개별 객실 갯수 많은거 찾아서 진행
room_list=df.room_name.unique()
room_list

array(['Double Room', 'Deluxe Twin Room', 'Deluxe Double Room', ...,
       'Family Room Two Double Beds', 'Small Room', '스몰룸 (Small Room)'],
      dtype=object)

In [6]:
# 각 호텔별로 방 이름의 빈도수 계산
room_counts = df.groupby('hotel_name')['room_name'].value_counts()

# 각 호텔별 상위 5개 방 이름 추출
top5_rooms_per_hotel = room_counts.groupby(level=0).nlargest(5).reset_index(level=0, drop=True)

In [7]:
top5_rooms_per_hotel

hotel_name        room_name
L7강남              스탠다드 트윈룸                                                                                              107558
                  스탠다드 더블룸                                                                                              104777
                  스탠다드 패밀리 트윈                                                                                            73975
                  스탠다드 더블 (Standard Double)                                                                              66548
                  수페리어 트윈룸                                                                                               65251
그랜드하얏트제주          킹룸 - 바다 전망                                                                                            109404
                  킹룸 - 도시 전망                                                                                            108882
                  트윈룸 - 바다 전망                                                                                           108311
                  코너 트윈 스위트룸                                                                                            108181
                  트윈룸 - 도시 전망                                                                                           106187
더플라자서울오토그래프컬렉션    디럭스룸 (킹베드) (Deluxe, Guest room, 1 King)                                                                45256
                  디럭스룸 (싱글베드 2개) (Deluxe Twin, Guest room, 2 Twin/Single Bed(s))                                         44278
                  디럭스룸 (킹베드, 클럽 라운지 이용 포함) (Club Deluxe, Club lounge access, Guest room, 1 King)                         41070
                  프리미어 스위트룸                                                                                              39944
                  디럭스 트윈룸, 트윈침대/싱글침대 2개                                                                                  39681
목시서울인사동호텔         스탠다드룸 (싱글베드 2개) (Standard Twin, Guest room, 2 Twin/Single Bed(s))                                      43447
                  슈페리어 시티뷰 룸 (싱글베드 2개) (Superior Twin, Guest room, 2 Twin/Single Bed(s), City view)                      43335
                  슈페리어 시티뷰 룸 (더블베드) (Superior Double, Guest room, 1 Double, City view)                                   43184
                  슈페리어 트윈 (주차불가)                                                                                         38706
                  수페리어 트윈룸                                                                                               36965
미포오션사이드호텔         디럭스 더블룸 - 바다 전망                                                                                        57720
                  오션 더블 (Ocean Double)                                                                                   57598
                  특별한 혜택 - 디럭스 더블룸 - 바다 전망                                                                               45043
                  시티 더블 (City Double)                                                                                    38442
                  수페리어 더블룸                                                                                               37692
베스트루이스해밀턴호텔광안점    1베드룸 스위트 (One-Bedroom Suite)                                                                           50372
                  수페리어 킹룸 (Superior King Room)                                                                           43553
                  Premium Half Ocean View Room                                                                           41296
                  시크 스퀘어 트윈룸 (Chic Square Twin Room)                                                                     41075
                  디럭스 킹룸 (Deluxe King.)                                                                                  40841
베이하운드호텔           스탠다드 더블룸                                                                                               87443
                  디럭스 더블 (Deluxe Double)                                                                                 79906
                  디럭스 트리플룸                                                                                               71827
                  스탠다드 더블 (Standard Double)                                                                              69416
                  디럭스 트리플 (Deluxe Triple)                                                                                64616
부산범일동브라운도트범일점부산역  디럭스 더블룸                                                                                               114290
                  디럭스 트윈룸                                                                                               103059
                  디럭스 킹룸                                                                                                102685
                  스탠다드 더블룸                                                                                              102493
                  패밀리 스위트룸                                                                                               96656
부산사상소르젠떼비지니스호텔    디럭스 킹룸 (Deluxe King Room)                                                                              37356
                  스위트룸 (Suite Room)                                                                                      36503
                  프리미엄룸 (Premium Room)                                                                                   36220
                  패밀리 스위트 (Family Suite)                                                                                 35086
                  프리미엄 트윈룸 (금연) (Premium Twin Room - Non-Smoking)                                                        34996
브라운도트호텔울산삼산       슈페리어 더블(Netflix 시청 가능)                                                                                 25929
                  그랜드 스위트(Netflix 시청 가능,스타일러)                                                                            25820
                  디럭스 트윈(Netflix 시청 가능)                                                                                  25740
                  ★특가★ 디럭스 더블(Netflix 시청 가능)                                                                             21754
                  24시 STAY                                                                                               21031
스위트호텔남원           디럭스 트윈룸                                                                                               129185
                  디럭스 트리플룸                                                                                              126130
                  디럭스 트윈룸 (Deluxe Twin Room)                                                                            109080
                  디럭스 트리플룸 (Deluxe Triple Room)                                                                         105849
                  빌라 체리                                                                                                  90461
신라스테이서초           스탠다드 더블룸                                                                                              138139
                  스탠다드 트윈룸                                                                                              128211
                  디럭스 더블룸                                                                                               116339
                  특별한 혜택 - 1인 여행객 패키지                                                                                   110545
                  프리미어 디럭스 더블룸 - 고층, 라운지 입장 포함, OTT TV 박스                                                               102164
신라스테이울산           디럭스 더블룸                                                                                               107090
                  스탠다드 더블룸                                                                                              106467
                  스탠다드 트윈룸                                                                                               92157
                  디럭스 더블 베드룸 (Deluxe Double Bed Room)                                                                    91862
                  프리미어 더블룸 (Premier Double Room)                                                                         84507
쏠비치진도호텔           리조트 스탠다드 스위트 (키친 없음) (Resort Standard Suite without Kitchen)                                           29346
                  스탠다드 트윈룸 (Twin Standard)                                                                               29166
                  호텔 슈페리어 오션뷰 패밀리 트윈룸 (키친 없음) (Hotel Superior Ocean View Family Twin Room without Kitchen)               28560
                  리조트 부분 오션뷰 스위트 (키친) (Resort Partial Ocean View Suite with Kitchen)                                     26010
                  리조트 오션뷰 패밀리룸 (키친 없음) (Resort Ocean View Family Room without Kitchen)                                   25933
아바니센트럴부산          디럭스 트윈룸 - 산 전망                                                                                        118584
                  스위트룸                                                                                                  118324
                  주니어 스위트룸                                                                                              117936
                  프리미어 더블룸                                                                                              116740
                  디럭스 트윈룸 - 도시 전망                                                                                       113927
완주힐링              디럭스 - B.B.Q 패키지                                                                                         9317
                  듀플렉스-오직 한 팀,패밀리 복층(넷플릭스무...                                                                             6771
                  더 편한 방-복층(월풀욕조/슈퍼킹+슈퍼킹/넷플릭스무료시청)                                                                        5730
                  듀플렉스-오직 한 팀,패밀리복층,B,.B.Q 패키...                                                                          5126
                  듀플렉스-패밀리 복층(넷플릭스무료/욕조/슈퍼킹+슈퍼킹)                                                                          4556
인천부평넘버25인천부평점     Superior room                                                                                          19765
                  Standard room                                                                                          19574
                  Deluxe couple P.C room (2PC, i5-10400,32인치 200Hz, GTX1660 6GB, 삼성16GB RAM, 사운드바, 넷플릭스)                 12354
                  Deluxe couple P.C room (2PC, i5-10400,32인...                                                            7468
                  Relax (빠른입실-늦은퇴실)                                                                                       7242
인천부평호텔주노          프리미엄커플PC(I5-8400&200Hz, GTX1060 6G, RAM16GB, 안마의자, 스타일러, 욕조,  공기청정기, PC전용시스템테이블, 의자, 기계식키보드, G102)     12360
                  [도보전용]커플PC룸(I5-CPU&게이밍모니터, GTX1060, RAM16GB, 욕조랜덤배정, 공기청정기, PC전용시스템테이블, 의자, 기계식키보드, G102,좌석랜덤)         12356
                  커플PC룸(I5-CPU&게이밍모니터, GTX1060, RAM16GB, 욕조랜덤배정, 공기청정기, PC전용시스템테이블, 의자, 기계식키보드, G102,좌석랜덤)               12356
                  스탠다드(싱글PC I5-4670, GTX960, RAM16GB, 공기청정기, 욕조 및 금연실 랜덤배정))                                             12355
                  스위트커플PC룸(I5-8400&165Hz, GTX1060 6G, RAM16GB, 안마의자, 욕조(랜덤배정), 공기청정기, PC전용시스템테이블, 의자, 기계식키보드, G102)      12355
중문리조트             패밀리 스위트                                                                                                37934
                  패밀리 스위트 (Family Suite)                                                                                 29291
                  패밀리 스위트룸                                                                                               28851
                  주니어 스위트                                                                                                28323
                  주니어 스위트룸                                                                                               15612
지앤지GG관광호텔부산대연동    디럭스 트윈(NETFLIX 무료 시청 가능)                                                                               38159
                  스카이(NETFLIX 무료 시청 가능)                                                                                  38117
                  프리미엄 코리안(NETFLIX 무료 시청 가능)                                                                             37587
                  디럭스 커플(NETFLIX 무료 시청 가능)                                                                               34437
                  스탠다드 더블(NETFLIX 무료 시청 가능)                                                                              27041
창원명서동시카고          빠른 입실                                                                                                  23927
                  스위트(넷플릭스,조식,스타일러,공기청정기)                                                                                23126
                  늦은 퇴실                                                                                                  21957
                  디럭스(넷플릭스,조식,스타일러,공기청정기)                                                                                18760
                  디럭스 트윈룸                                                                                                15978
파크하얏트부산           패밀리 스위트룸                                                                                              124869
                  이그제큐티브 패밀리 스위트룸                                                                                       105871
                  오션뷰 킹룸                                                                                                 81866
                  디럭스 킹룸                                                                                                 78738
                  킹룸                                                                                                     77200
해비치호텔리조트          호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village View Twin Room)                                             37569
                  호텔 - 디럭스 씨사이드 트윈룸 (Hotel Deluxe Seaside Twin Room)                                                     34327
                  [호텔] 슈페리어 빌리지 트윈                                                                                       32966
                  호텔 - 슈페리어 빌리지뷰 킹룸 (Hotel Superior Village View King Room)                                              32425
                  호텔 - 이그제큐티브 오션뷰 트윈룸 (Hotel Executive Ocean View Twin Room)                                             31901
호메르스호텔            비즈니스 트윈룸 (BUSINESS TWIN BED ROOM)                                                                      42457
                  하이 디럭스 더블 (High Deluxe Double)                                                                         41884
                  디럭스 더블 (오션뷰) (Deluxe Double - Ocean View)                                                              39790
                  디럭스 트윈룸 - 오션뷰 (Deluxe Twin Room - Ocean view)                                                          37940
                  비즈니스 더블베드 (Business Double Bed)                                                                        37699
호텔라싸              디럭스룸 (Deluxe Room)                                                                                     32547
                  Suite (넷플릭스 시청가능)                                                                                      30680
                  Royal Suite (넷플릭스 시청가능)                                                                                30080
                  스탠다드룸 (Standard Room)                                                                                  29892
                  Deluxe-연박가능 Early cheek-in (주차가능,n...                                                                  18481
호텔브라운도트광안비치점      트윈(넷플릭스, PC, 욕조)                                                                                       18307
                  테라스 프리미엄(넷플릭스, PC, 욕조 ,쇼파)                                                                             18269
                  디럭스(넷플릭스, PC, 욕조)                                                                                      17022
                  스탠다드(넷플릭스, PC, 욕조)                                                                                     13249
                  디럭스룸 (Deluxe )                                                                                         11236
호텔인나인             주니어 스위트룸                                                                                              189880
                  스탠다드 더블룸                                                                                              172968
                  스탠다드 트윈룸                                                                                              170168
                  디럭스 더블 코너룸                                                                                            162548
                  디럭스 더블룸 - 목재 바닥, 3층에 위치                                                                               161997
호텔케이월드            SUITE                                                                                                  36899
                  PREMIUM DOUBLE                                                                                         36692
                  PREMIUM TWIN                                                                                           36431
                  DELUXE TWIN                                                                                            33247
                  DELUXE DOUBLE                                                                                          31350
호텔페이토삼성           디럭스 더블룸                                                                                                98880
                  어반룸 (Urban Room)                                                                                       88136
                  디럭스 더블 (Deluxe Double)                                                                                 87079
                  디럭스 트윈룸                                                                                                83684
                  디럭스 트윈 (Deluxe Twin)                                                                                   72693
힐튼호텔경주            디럭스 트리플룸                                                                                              115038
                  이그제큐티브 킹 스위트 (King Executive Suite)                                                                    94996
                  이그제큐티브 프리미엄 킹 스위트 (King Executive Premium Suite)                                                       93056
                  이그제큐티브 킹 스위트룸                                                                                          91177
                  에스페로 스위트 (Espero Suite)                                                                                90014
Name: count, dtype: int64

In [8]:
top5_rooms_df = top5_rooms_per_hotel.reset_index(name='counts')
top5_rooms_df

,hotel_name,room_name,counts
0,L7강남,스탠다드 트윈룸,107558
1,L7강남,스탠다드 더블룸,104777
2,L7강남,스탠다드 패밀리 트윈,73975
3,L7강남,스탠다드 더블 (Standard Double),66548
4,L7강남,수페리어 트윈룸,65251
5,그랜드하얏트제주,킹룸 - 바다 전망,109404
6,그랜드하얏트제주,킹룸 - 도시 전망,108882
7,그랜드하얏트제주,트윈룸 - 바다 전망,108311
8,그랜드하얏트제주,코너 트윈 스위트룸,108181
9,그랜드하얏트제주,트윈룸 - 도시 전망,106187
10,더플라자서울오토그래프컬렉션,"디럭스룸 (킹베드) (Deluxe, Guest room, 1 King)",45256
11,더플라자서울오토그래프컬렉션,"디럭스룸 (싱글베드 2개) (Deluxe Twin, Guest room, 2 Twi...",44278
12,더플라자서울오토그래프컬렉션,"디럭스룸 (킹베드, 클럽 라운지 이용 포함) (Club Deluxe, Club lo...",41070
13,더플라자서울오토그래프컬렉션,프리미어 스위트룸,39944
14,더플라자서울오토그래프컬렉션,"디럭스 트윈룸, 트윈침대/싱글침대 2개",39681
15,목시서울인사동호텔,"스탠다드룸 (싱글베드 2개) (Standard Twin, Guest room, 2 ...",43447
16,목시서울인사동호텔,"슈페리어 시티뷰 룸 (싱글베드 2개) (Superior Twin, Guest roo...",43335
17,목시서울인사동호텔,"슈페리어 시티뷰 룸 (더블베드) (Superior Double, Guest room...",43184
18,목시서울인사동호텔,슈페리어 트윈 (주차불가),38706
19,목시서울인사동호텔,수페리어 트윈룸,36965
20,미포오션사이드호텔,디럭스 더블룸 - 바다 전망,57720
21,미포오션사이드호텔,오션 더블 (Ocean Double),57598
22,미포오션사이드호텔,특별한 혜택 - 디럭스 더블룸 - 바다 전망,45043
23,미포오션사이드호텔,시티 더블 (City Double),38442
24,미포오션사이드호텔,수페리어 더블룸,37692
25,베스트루이스해밀턴호텔광안점,1베드룸 스위트 (One-Bedroom Suite),50372
26,베스트루이스해밀턴호텔광안점,수페리어 킹룸 (Superior King Room),43553
27,베스트루이스해밀턴호텔광안점,Premium Half Ocean View Room,41296
28,베스트루이스해밀턴호텔광안점,시크 스퀘어 트윈룸 (Chic Square Twin Room),41075
29,베스트루이스해밀턴호텔광안점,디럭스 킹룸 (Deluxe King.),40841
30,베이하운드호텔,스탠다드 더블룸,87443
31,베이하운드호텔,디럭스 더블 (Deluxe Double),79906
32,베이하운드호텔,디럭스 트리플룸,71827
33,베이하운드호텔,스탠다드 더블 (Standard Double),69416
34,베이하운드호텔,디럭스 트리플 (Deluxe Triple),64616
35,부산범일동브라운도트범일점부산역,디럭스 더블룸,114290
36,부산범일동브라운도트범일점부산역,디럭스 트윈룸,103059
37,부산범일동브라운도트범일점부산역,디럭스 킹룸,102685
38,부산범일동브라운도트범일점부산역,스탠다드 더블룸,102493
39,부산범일동브라운도트범일점부산역,패밀리 스위트룸,96656
40,부산사상소르젠떼비지니스호텔,디럭스 킹룸 (Deluxe King Room),37356
41,부산사상소르젠떼비지니스호텔,스위트룸 (Suite Room),36503
42,부산사상소르젠떼비지니스호텔,프리미엄룸 (Premium Room),36220
43,부산사상소르젠떼비지니스호텔,패밀리 스위트 (Family Suite),35086
44,부산사상소르젠떼비지니스호텔,프리미엄 트윈룸 (금연) (Premium Twin Room - Non-Smoking),34996
45,브라운도트호텔울산삼산,슈페리어 더블(Netflix 시청 가능),25929
46,브라운도트호텔울산삼산,"그랜드 스위트(Netflix 시청 가능,스타일러)",25820
47,브라운도트호텔울산삼산,디럭스 트윈(Netflix 시청 가능),25740
48,브라운도트호텔울산삼산,★특가★ 디럭스 더블(Netflix 시청 가능),21754
49,브라운도트호텔울산삼산,24시 STAY,21031
50,스위트호텔남원,디럭스 트윈룸,129185
51,스위트호텔남원,디럭스 트리플룸,126130
52,스위트호텔남원,디럭스 트윈룸 (Deluxe Twin Room),109080
53,스위트호텔남원,디럭스 트리플룸 (Deluxe Triple Room),105849
54,스위트호텔남원,빌라 체리,90461
55,신라스테이서초,스탠다드 더블룸,138139
56,신라스테이서초,스탠다드 트윈룸,128211
57,신라스테이서초,디럭스 더블룸,116339
58,신라스테이서초,특별한 혜택 - 1인 여행객 패키지,110545
59,신라스테이서초,"프리미어 디럭스 더블룸 - 고층, 라운지 입장 포함, OTT TV 박스",102164
60,신라스테이울산,디럭스 더블룸,107090
61,신라스테이울산,스탠다드 더블룸,106467
62,신라스테이울산,스탠다드 트윈룸,92157
63,신라스테이울산,디럭스 더블 베드룸 (Deluxe Double Bed Room),91862
64,신라스테이울산,프리미어 더블룸 (Premier Double Room),84507
65,쏠비치진도호텔,리조트 스탠다드 스위트 (키친 없음) (Resort Standard Suite wi...,29346
66,쏠비치진도호텔,스탠다드 트윈룸 (Twin Standard),29166
67,쏠비치진도호텔,호텔 슈페리어 오션뷰 패밀리 트윈룸 (키친 없음) (Hotel Superior Oc...,28560
68,쏠비치진도호텔,리조트 부분 오션뷰 스위트 (키친) (Resort Partial Ocean View...,26010
69,쏠비치진도호텔,리조트 오션뷰 패밀리룸 (키친 없음) (Resort Ocean View Family...,25933
70,아바니센트럴부산,디럭스 트윈룸 - 산 전망,118584
71,아바니센트럴부산,스위트룸,118324
72,아바니센트럴부산,주니어 스위트룸,117936
73,아바니센트럴부산,프리미어 더블룸,116740
74,아바니센트럴부산,디럭스 트윈룸 - 도시 전망,113927
75,완주힐링,디럭스 - B.B.Q 패키지,9317
76,완주힐링,"듀플렉스-오직 한 팀,패밀리 복층(넷플릭스무...",6771
77,완주힐링,더 편한 방-복층(월풀욕조/슈퍼킹+슈퍼킹/넷플릭스무료시청),5730
78,완주힐링,"듀플렉스-오직 한 팀,패밀리복층,B,.B.Q 패키...",5126
79,완주힐링,듀플렉스-패밀리 복층(넷플릭스무료/욕조/슈퍼킹+슈퍼킹),4556
80,인천부평넘버25인천부평점,Superior room,19765
81,인천부평넘버25인천부평점,Standard room,19574
82,인천부평넘버25인천부평점,"Deluxe couple P.C room (2PC, i5-10400,32인치 200...",12354
83,인천부평넘버25인천부평점,"Deluxe couple P.C room (2PC, i5-10400,32인...",7468
84,인천부평넘버25인천부평점,Relax (빠른입실-늦은퇴실),7242
85,인천부평호텔주노,"프리미엄커플PC(I5-8400&200Hz, GTX1060 6G, RAM16GB, 안...",12360
86,인천부평호텔주노,"[도보전용]커플PC룸(I5-CPU&게이밍모니터, GTX1060, RAM16GB, 욕...",12356
87,인천부평호텔주노,"커플PC룸(I5-CPU&게이밍모니터, GTX1060, RAM16GB, 욕조랜덤배정,...",12356
88,인천부평호텔주노,"스탠다드(싱글PC I5-4670, GTX960, RAM16GB, 공기청정기, 욕조 ...",12355
89,인천부평호텔주노,"스위트커플PC룸(I5-8400&165Hz, GTX1060 6G, RAM16GB, 안...",12355
90,중문리조트,패밀리 스위트,37934
91,중문리조트,패밀리 스위트 (Family Suite),29291
92,중문리조트,패밀리 스위트룸,28851
93,중문리조트,주니어 스위트,28323
94,중문리조트,주니어 스위트룸,15612
95,지앤지GG관광호텔부산대연동,디럭스 트윈(NETFLIX 무료 시청 가능),38159
96,지앤지GG관광호텔부산대연동,스카이(NETFLIX 무료 시청 가능),38117
97,지앤지GG관광호텔부산대연동,프리미엄 코리안(NETFLIX 무료 시청 가능),37587
98,지앤지GG관광호텔부산대연동,디럭스 커플(NETFLIX 무료 시청 가능),34437
99,지앤지GG관광호텔부산대연동,스탠다드 더블(NETFLIX 무료 시청 가능),27041
100,창원명서동시카고,빠른 입실,23927
101,창원명서동시카고,"스위트(넷플릭스,조식,스타일러,공기청정기)",23126
102,창원명서동시카고,늦은 퇴실,21957
103,창원명서동시카고,"디럭스(넷플릭스,조식,스타일러,공기청정기)",18760
104,창원명서동시카고,디럭스 트윈룸,15978
105,파크하얏트부산,패밀리 스위트룸,124869
106,파크하얏트부산,이그제큐티브 패밀리 스위트룸,105871
107,파크하얏트부산,오션뷰 킹룸,81866
108,파크하얏트부산,디럭스 킹룸,78738
109,파크하얏트부산,킹룸,77200
110,해비치호텔리조트,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,37569
111,해비치호텔리조트,호텔 - 디럭스 씨사이드 트윈룸 (Hotel Deluxe Seaside Twin R...,34327
112,해비치호텔리조트,[호텔] 슈페리어 빌리지 트윈,32966
113,해비치호텔리조트,호텔 - 슈페리어 빌리지뷰 킹룸 (Hotel Superior Village View...,32425
114,해비치호텔리조트,호텔 - 이그제큐티브 오션뷰 트윈룸 (Hotel Executive Ocean Vie...,31901
115,호메르스호텔,비즈니스 트윈룸 (BUSINESS TWIN BED ROOM),42457
116,호메르스호텔,하이 디럭스 더블 (High Deluxe Double),41884
117,호메르스호텔,디럭스 더블 (오션뷰) (Deluxe Double - Ocean View),39790
118,호메르스호텔,디럭스 트윈룸 - 오션뷰 (Deluxe Twin Room - Ocean view),37940
119,호메르스호텔,비즈니스 더블베드 (Business Double Bed),37699
120,호텔라싸,디럭스룸 (Deluxe Room),32547
121,호텔라싸,Suite (넷플릭스 시청가능),30680
122,호텔라싸,Royal Suite (넷플릭스 시청가능),30080
123,호텔라싸,스탠다드룸 (Standard Room),29892
124,호텔라싸,"Deluxe-연박가능 Early cheek-in (주차가능,n...",18481
125,호텔브라운도트광안비치점,"트윈(넷플릭스, PC, 욕조)",18307
126,호텔브라운도트광안비치점,"테라스 프리미엄(넷플릭스, PC, 욕조 ,쇼파)",18269
127,호텔브라운도트광안비치점,"디럭스(넷플릭스, PC, 욕조)",17022
128,호텔브라운도트광안비치점,"스탠다드(넷플릭스, PC, 욕조)",13249
129,호텔브라운도트광안비치점,디럭스룸 (Deluxe ),11236
130,호텔인나인,주니어 스위트룸,189880
131,호텔인나인,스탠다드 더블룸,172968
132,호텔인나인,스탠다드 트윈룸,170168
133,호텔인나인,디럭스 더블 코너룸,162548
134,호텔인나인,"디럭스 더블룸 - 목재 바닥, 3층에 위치",161997
135,호텔케이월드,SUITE,36899
136,호텔케이월드,PREMIUM DOUBLE,36692
137,호텔케이월드,PREMIUM TWIN,36431
138,호텔케이월드,DELUXE TWIN,33247
139,호텔케이월드,DELUXE DOUBLE,31350
140,호텔페이토삼성,디럭스 더블룸,98880
141,호텔페이토삼성,어반룸 (Urban Room),88136
142,호텔페이토삼성,디럭스 더블 (Deluxe Double),87079
143,호텔페이토삼성,디럭스 트윈룸,83684
144,호텔페이토삼성,디럭스 트윈 (Deluxe Twin),72693
145,힐튼호텔경주,디럭스 트리플룸,115038
146,힐튼호텔경주,이그제큐티브 킹 스위트 (King Executive Suite),94996
147,힐튼호텔경주,이그제큐티브 프리미엄 킹 스위트 (King Executive Premium Suite),93056
148,힐튼호텔경주,이그제큐티브 킹 스위트룸,91177
149,힐튼호텔경주,에스페로 스위트 (Espero Suite),90014

In [11]:
# 각 호텔별로 방 이름의 빈도수 계산
room_counts = df.groupby('hotel_name')['room_id'].value_counts()

# 각 호텔별 상위 5개 방 이름 추출
top5_rooms_per_hotel = room_counts.groupby(level=0).nlargest(5).reset_index(level=0, drop=True)
top5_rooms_number = top5_rooms_per_hotel.reset_index(name='counts')
top5_rooms_number

           hotel_name    room_id  counts
0                L7강남       9461   75063
1                L7강남       9462   71113
2                L7강남       7855   66536
3                L7강남       9470   65089
4                L7강남       9469   64799
5            그랜드하얏트제주   35482131  109404
6            그랜드하얏트제주   36987283  108882
7            그랜드하얏트제주   35482132  108311
8            그랜드하얏트제주   35580397  108181
9            그랜드하얏트제주   31760941  106187
10     더플라자서울오토그래프컬렉션      33179   45210
11     더플라자서울오토그래프컬렉션      33178   44220
12     더플라자서울오토그래프컬렉션      33181   41020
13     더플라자서울오토그래프컬렉션      45039   39784
14     더플라자서울오토그래프컬렉션    1060885   39580
15          목시서울인사동호텔      12176   43379
16          목시서울인사동호텔      12177   43275
17          목시서울인사동호텔      12178   43124
18          목시서울인사동호텔      11251   38523
19          목시서울인사동호텔      44218   36782
20          미포오션사이드호텔       8950   57695
21          미포오션사이드호텔       9131   57538
22          미포오션사이드호텔       8951   45018
23          미포오션사이드호텔       9133   38427
24          미포오션사이드호텔       8949   37687
25     베스트루이스해밀턴호텔광안점       6133   50336
26     베스트루이스해밀턴호텔광안점       6127   43513
27     베스트루이스해밀턴호텔광안점       6131   41245
28     베스트루이스해밀턴호텔광안점       6130   41008
29     베스트루이스해밀턴호텔광안점    1061220   40841
30            베이하운드호텔      13004   79846
31            베이하운드호텔      13001   69356
32            베이하운드호텔      13005   64567
33            베이하운드호텔     310213   60461
34            베이하운드호텔      13000   55971
35   부산범일동브라운도트범일점부산역       5153  114147
36   부산범일동브라운도트범일점부산역       5156  102940
37   부산범일동브라운도트범일점부산역       5155  102566
38   부산범일동브라운도트범일점부산역       5152  102374
39   부산범일동브라운도트범일점부산역       5161   96573
40     부산사상소르젠떼비지니스호텔      15178   37292
41     부산사상소르젠떼비지니스호텔      15192   36436
42     부산사상소르젠떼비지니스호텔      15187   36160
43     부산사상소르젠떼비지니스호텔      15193   34991
44     부산사상소르젠떼비지니스호텔      15189   34933
45        브라운도트호텔울산삼산    1043567   25898
46        브라운도트호텔울산삼산    1043588   25818
47        브라운도트호텔울산삼산    1043570   25718
48        브라운도트호텔울산삼산    1043559   21723
49        브라운도트호텔울산삼산    1043586   20818
50            스위트호텔남원       2611  109021
51            스위트호텔남원       2031  105751
52            스위트호텔남원   15171206   87153
53            스위트호텔남원       2975   80661
54            스위트호텔남원       1481   78145
55            신라스테이서초       7195  117833
56            신라스테이서초       7198  115710
57            신라스테이서초       7197  110534
58            신라스테이서초       7200  109912
59            신라스테이서초       7199  101596
60            신라스테이울산       8260   91792
61            신라스테이울산       8264   84439
62            신라스테이울산       8256   78333
63            신라스테이울산       8266   64494
64            신라스테이울산       8262   62932
65            쏠비치진도호텔  174349486   29346
66            쏠비치진도호텔      21567   29158
67            쏠비치진도호텔  174349483   28560
68            쏠비치진도호텔  174349492   26010
69            쏠비치진도호텔  174349490   25933
70           아바니센트럴부산      41928  118457
71           아바니센트럴부산      41932  118203
72           아바니센트럴부산      41931  117817
73           아바니센트럴부산      41930  116617
74           아바니센트럴부산      41929  113812
75               완주힐링    1040935    9205
76               완주힐링    6713787    6771
77               완주힐링   -5684392    5730
78               완주힐링    6713789    5126
79               완주힐링   -5682221    4556
80      인천부평넘버25인천부평점    1040707   19707
81      인천부평넘버25인천부평점    1040705   19574
82      인천부평넘버25인천부평점   -5680658   12354
83      인천부평넘버25인천부평점    1040706    7408
84      인천부평넘버25인천부평점    6713510    7242
85           인천부평호텔주노   -5654172   12360
86           인천부평호텔주노   -5674176   12356
87           인천부평호텔주노   -5667252   12356
88           인천부평호텔주노   -5675930   12355
89           인천부평호텔주노   -5674313   12355
90              중문리조트      14887   37862
91              중문리조트     202474   29246
92              중문리조트      19394   28414
93              중문리조트      14886   28231
94              중문리조트      19395   15366
95     지앤지GG관광호텔부산대연동    1037350   38047
96     지앤지GG관광호텔부산대연동    1037321   37993
97     지앤지GG관광호텔부산대연동    1037318   37463
98     지앤지GG관광호텔부산대연동    1037316   34331
99     지앤지GG관광호텔부산대연동    1037315   26940
100          창원명서동시카고    1040747   23853
101          창원명서동시카고    1040735   23050
102          창원명서동시카고    1040733   21881
103          창원명서동시카고    1040744   18686
104          창원명서동시카고  154926341   15978
105           파크하얏트부산      45332  124753
106           파크하얏트부산      45333  105821
107           파크하얏트부산  147794966   81866
108           파크하얏트부산  147774069   78738
109           파크하얏트부산  147794965   77200
110          해비치호텔리조트      12557   37493
111          해비치호텔리조트      12790   34242
112          해비치호텔리조트      11588   32860
113          해비치호텔리조트      12919   32353
114          해비치호텔리조트      13014   31837
115            호메르스호텔       8278   42358
116            호메르스호텔       8281   41806
117            호메르스호텔       8641   39700
118            호메르스호텔       8280   37852
119            호메르스호텔       8277   37613
120              호텔라싸      12608   32499
121              호텔라싸    1040349   30603
122              호텔라싸    1040350   30013
123              호텔라싸      12609   29843
124              호텔라싸   14966052   18481
125      호텔브라운도트광안비치점    1040370   18220
126      호텔브라운도트광안비치점    1040369   18197
127      호텔브라운도트광안비치점    1040368   16918
128      호텔브라운도트광안비치점    1040365   13145
129      호텔브라운도트광안비치점  -26681427   11236
130             호텔인나인       7561  189419
131             호텔인나인       7558  172433
132             호텔인나인       7559  169635
133             호텔인나인       7560  162079
134             호텔인나인       8846  161464
135            호텔케이월드    1040342   36777
136            호텔케이월드    1040339   36571
137            호텔케이월드    1040340   36310
138            호텔케이월드    1040337   33131
139            호텔케이월드    1040336   31229
140           호텔페이토삼성       8500   88046
141           호텔페이토삼성       8498   87004
142           호텔페이토삼성       8499   72606
143           호텔페이토삼성      42149   72116
144           호텔페이토삼성      42224   66632
145            힐튼호텔경주       7143   94904
146            힐튼호텔경주       7759   92985
147            힐튼호텔경주      42032   91005
148            힐튼호텔경주       7145   89996
149            힐튼호텔경주       7137   89874

In [12]:
# 해당 조건 필터
df=df[df['room_id'].isin(top5_rooms_number['room_id'])]
df

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,region,room_name,hotel_name,hoteLgrade,객실수,업태구분명
15710,1535,1040733,2022-01-01,2022-01-01 11:00:00,1,70000,-1 days +13:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
15711,1535,1040733,2022-01-01,2022-01-01 23:00:00,1,60000,-1 days +01:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
15712,1535,1040733,2022-01-02,2022-01-01 11:00:00,1,70000,0 days 13:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
15713,1535,1040733,2022-01-02,2022-01-01 23:00:00,1,60000,0 days 01:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
15714,1535,1040733,2022-01-02,2022-01-02 11:00:00,1,60000,-1 days +13:00:00,2022-01-02,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48011505,1652,202474,2023-10-23,2023-09-24 12:00:00,1,100000,28 days 12:00:00,2023-09-24,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주
48011506,1652,202474,2023-10-23,2023-09-25 17:00:00,1,100000,27 days 07:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주
48011507,1652,202474,2023-10-23,2023-09-25 23:00:00,1,100000,27 days 01:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주
48011508,1652,202474,2023-10-24,2023-09-25 17:00:00,1,100000,28 days 07:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주
48011509,1652,202474,2023-10-24,2023-09-25 23:00:00,1,100000,28 days 01:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주

In [13]:
# 날짜 데이터가 있는 열을 datetime 타입으로 변환
df['booking_date'] = pd.to_datetime(df['booking_date'])
df['scanned_date'] = pd.to_datetime(df['scanned_date'])
df['scanned_date_date'] = pd.to_datetime(df['scanned_date_date'])

In [14]:
# timedelta로 전환
df['date_diff'] = pd.to_timedelta(df['date_diff'])
df

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,region,room_name,hotel_name,hoteLgrade,객실수,업태구분명
15710,1535,1040733,2022-01-01,2022-01-01 11:00:00,1,70000,-1 days +13:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
15711,1535,1040733,2022-01-01,2022-01-01 23:00:00,1,60000,-1 days +01:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
15712,1535,1040733,2022-01-02,2022-01-01 11:00:00,1,70000,0 days 13:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
15713,1535,1040733,2022-01-02,2022-01-01 23:00:00,1,60000,0 days 01:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
15714,1535,1040733,2022-01-02,2022-01-02 11:00:00,1,60000,-1 days +13:00:00,2022-01-02,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48011505,1652,202474,2023-10-23,2023-09-24 12:00:00,1,100000,28 days 12:00:00,2023-09-24,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주
48011506,1652,202474,2023-10-23,2023-09-25 17:00:00,1,100000,27 days 07:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주
48011507,1652,202474,2023-10-23,2023-09-25 23:00:00,1,100000,27 days 01:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주
48011508,1652,202474,2023-10-24,2023-09-25 17:00:00,1,100000,28 days 07:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주
48011509,1652,202474,2023-10-24,2023-09-25 23:00:00,1,100000,28 days 01:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주

In [15]:
# leadtime 만들기 

# 조건과 선택지 자동 생성
conditions = [(df['date_diff'].dt.days >= i) & (df['date_diff'].dt.days < i+1) for i in range(-1, 30)]
choices = [i for i in range(31)]

# 'lead_time' 열 생성
df['lead_time'] = np.select(conditions, choices, default=np.nan)

In [16]:
# scanned_date 열에서 시간 정보만을 추출하여 scanned_date_time 열에 저장
df['scanned_date_time'] = df['scanned_date'].dt.time

# 데이터 정의

* 하나의 북킹데이트 1  그리고 하나의 스캔데이트에 가격데이터는  포함하면 0개 일수도 있다
* 종가를 예측하자 어느 시간대든 하나만 추적할텐데 둘개 중에서 그래도 좀 더 마감가에 가까울걸 찾는게 좋을듯하다
* region, hotel_grade, 객실수, 업태구분명, ota_type은 데이터 전처리 과정에서는 필요없다. 나중에는 없이 불러올수 있도록하자

In [4]:
df=pd.read_csv("hotel_price_raw_filtered.csv")
df

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,region,room_name,hotel_name,hoteLgrade,객실수,업태구분명,lead_time,scanned_date_time
0,1535,1040733,2022-01-01,2022-01-01 11:00:00,1,70000,-1 days +13:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류,0,11:00:00
1,1535,1040733,2022-01-01,2022-01-01 23:00:00,1,60000,-1 days +01:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류,0,23:00:00
2,1535,1040733,2022-01-02,2022-01-01 11:00:00,1,70000,0 days 13:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류,1,11:00:00
3,1535,1040733,2022-01-02,2022-01-01 23:00:00,1,60000,0 days 01:00:00,2022-01-01,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류,1,23:00:00
4,1535,1040733,2022-01-02,2022-01-02 11:00:00,1,60000,-1 days +13:00:00,2022-01-02,GOODCHOICE,경상,늦은 퇴실,창원명서동시카고,미등급,미분류,미분류,0,11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8529231,1652,202474,2023-10-23,2023-09-24 12:00:00,1,100000,28 days 12:00:00,2023-09-24,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주,29,12:00:00
8529232,1652,202474,2023-10-23,2023-09-25 17:00:00,1,100000,27 days 07:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주,28,17:00:00
8529233,1652,202474,2023-10-23,2023-09-25 23:00:00,1,100000,27 days 01:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주,28,23:00:00
8529234,1652,202474,2023-10-24,2023-09-25 17:00:00,1,100000,28 days 07:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주,29,17:00:00
8529235,1652,202474,2023-10-24,2023-09-25 23:00:00,1,100000,28 days 01:00:00,2023-09-25,AGODA,제주,패밀리 스위트 (Family Suite),중문리조트,1성,44,가족호텔_제주,29,23:00:00

In [34]:
df2=df[['hotel_id','room_id','region','객실수','업태구분명','hoteLgrade']].drop_duplicates()
df2

         hotel_id    room_id region    객실수    업태구분명 hoteLgrade
0            1535    1040733     경상    미분류      미분류        미등급
21881        1535    1040735     경상    미분류      미분류        미등급
44931        1535    1040744     경상    미분류      미분류        미등급
63617        1535    1040747     경상    미분류      미분류        미등급
87470        1535  154926341     경상    미분류      미분류        미등급
103448       1309       7143     경상  330.0    관광호텔업         5성
131072       1309       7143     경상    330    관광호텔업         5성
198352       1309       7145     경상    330    관광호텔업         5성
288348       1309       7759     경상    330    관광호텔업         5성
381333       1309      42032     경상    330    관광호텔업         5성
472338       1309       7137     경상    330    관광호텔업         5성
562212       1414    1040365     부산     29    소형호텔업         1성
575357       1414    1040368     부산     29    소형호텔업         1성
592275       1414    1040369     부산     29    소형호텔업         1성
610472       1414    1040370     부산     29    소형호텔업         1성
628692       1414  -26681427     부산     29    소형호텔업         1성
639928       1589      15193     부산     46    관광호텔업         2성
674919       1589      15178     부산     46    관광호텔업         2성
712211       1589      15187     부산     46    관광호텔업         2성
748371       1589      15189     부산     46    관광호텔업         2성
783304       1589      15192     부산     46    관광호텔업         2성
819740       1442       5152     부산     48     일반호텔        미등급
922114       1442       5153     부산     48     일반호텔        미등급
1036261      1442       5155     부산     48     일반호텔        미등급
1138827      1442       5156     부산     48     일반호텔        미등급
1241767      1442       5161     부산     48     일반호텔        미등급
1338340       250       8277     부산    143    관광호텔업         3성
1375953       250       8278     부산    143    관광호텔업         3성
1418311       250       8280     부산    143    관광호텔업         3성
1456163       250       8281     부산    143    관광호텔업         3성
1497969       250       8641     부산    143    관광호텔업         3성
1537669       257       6127     부산     50    관광호텔업         2성
1581182       257       6133     부산     50    관광호텔업         2성
1631518       257       6130     부산     50    관광호텔업         2성
1672526       257       6131     부산     50    관광호텔업         2성
1713771       257    1061220     부산     50    관광호텔업         2성
1754612       139      41928     부산    281    관광호텔업         4성
1873069       139      41929     부산    281    관광호텔업         4성
1986881       139      41930     부산    281    관광호텔업         4성
2103498       139      41931     부산    281    관광호텔업         4성
2221315       139      41932     부산    281    관광호텔업         4성
2339518       271    1037315     부산     41    관광호텔업         2성
2366458       271    1037316     부산     41    관광호텔업         2성
2400789       271    1037318     부산     41    관광호텔업         2성
2438252       271    1037321     부산     41    관광호텔업         2성
2476245       271    1037350     부산     41    관광호텔업         2성
2514292       312       8949     부산     28    소형호텔업         2성
2551979       312       8950     부산     28    소형호텔업         2성
2609674       312       8951     부산     28    소형호텔업         2성
2654692       312       9131     부산     28    소형호텔업         2성
2712230       312       9133     부산     28    소형호텔업         2성
2750657       269      13000     부산     69    관광호텔업         2성
2806628       269      13001     부산     69    관광호텔업         2성
2875984       269      13004     부산     69    관광호텔업         2성
2955830       269      13005     부산     69    관광호텔업         2성
3020397       269     310213     부산     69    관광호텔업         2성
3080858       302      45332     부산    269    관광호텔업         5성
3205611       302      45333     부산    269    관광호텔업         5성
3311432       302  147794966     부산    269    관광호텔업         5성
3393298       302  147774069     부산    269    관광호텔업         5성
3472036       302  147794965     부산    269    관광호텔업         5성
3549236      1009      12608     서울     44    관광호텔업         1성
3581735      1009      12609     서울     44    관광호텔업         1성
3611578      1009    1040349     서울     44    관광호텔업         1성
3642181      1009    1040350     서울     44    관광호텔업         1성
3672194      1009   14966052     서울     44    관광호텔업         1성
3690675      1095       7195     서울    305    관광호텔업         3성
3808508      1095       7197     서울    305    관광호텔업         3성
3919042      1095       7198     서울    305    관광호텔업         3성
4034752      1095       7200     서울    305    관광호텔업         3성
4144664      1095       7199     서울    305    관광호텔업         3성
4246260       351      11251     서울    140    관광호텔업         3성
4284783       351      12176     서울    140    관광호텔업         3성
4328162       351      12177     서울    140    관광호텔업         3성
4371437       351      12178     서울    140    관광호텔업         3성
4414561       351      44218     서울    140    관광호텔업         3성
4451343      1378       7855     서울    333    관광호텔업         4성
4517879      1378       9461     서울    333    관광호텔업         4성
4592942      1378       9462     서울    333    관광호텔업         4성
4664055      1378       9469     서울    333    관광호텔업         4성
4728854      1378       9470     서울    333    관광호텔업         4성
4793943      1387       7558     서울    151    관광호텔업         4성
4966376      1387       7559     서울    151    관광호텔업         4성
5136011      1387       7560     서울    151    관광호텔업         4성
5298090      1387       7561     서울    151    관광호텔업         4성
5487509      1387       8846     서울    151    관광호텔업         4성
5648973      1367       8498     서울    163    관광호텔업         3성
5735977      1367       8499     서울    163    관광호텔업         3성
5808583      1367      42149     서울    163    관광호텔업         3성
5880699      1367       8500     서울    163    관광호텔업         3성
5968745      1367      42224     서울    163    관광호텔업         3성
6035377       143      33178     서울    410    관광호텔업         5성
6079597       143      33179     서울    410    관광호텔업         5성
6124807       143      33181     서울    410    관광호텔업         5성
6165827       143      45039     서울    410    관광호텔업         5성
6205611       143    1060885     서울    410    관광호텔업         5성
6245191       980    1040336     서울     54    관광호텔업         1성
6276420       980    1040337     서울     54    관광호텔업         1성
6309551       980    1040339     서울     54    관광호텔업         1성
6346122       980    1040340     서울     54    관광호텔업         1성
6382432       980    1040342     서울     54    관광호텔업         1성
6419209       217       8256     울산    335    관광호텔업         3성
6497542       217       8260     울산    335    관광호텔업         3성
6589334       217       8262     울산    335    관광호텔업         3성
6652266       217       8264     울산    335    관광호텔업         3성
6736705       217       8266     울산    335    관광호텔업         3성
6801199      1669    1043559     울산     50    관광호텔업         1성
6822922      1669    1043567     울산     50    관광호텔업         1성
6848820      1669    1043570     울산     50    관광호텔업         1성
6874538      1669    1043586     울산     50    관광호텔업         1성
6895356      1669    1043588     울산     50    관광호텔업         1성
6921174      1525   -5680658     인천     34      여관업        미등급
6933528      1525    1040705     인천     34      여관업        미등급
6953102      1525    1040707     인천     34      여관업        미등급
6972809      1525    1040706     인천     34      여관업        미등급
6979584      1525    1040706     인천   34.0      여관업        미등급
6980217      1525    6713510     인천   34.0      여관업        미등급
6987459      1526   -5675930     인천    미분류      미분류        미등급
6999814      1526   -5674313     인천    미분류      미분류        미등급
7012169      1526   -5674176     인천    미분류      미분류        미등급
7024525      1526   -5667252     인천    미분류      미분류        미등급
7036881      1526   -5654172     인천    미분류      미분류        미등급
7049241       818      21567     전라   98.0    관광호텔업         4성
7077888       818      21567     전라     98    관광호텔업         4성
7078399       818  174349483     전라     98    관광호텔업         4성
7106959       818  174349486     전라     98    관광호텔업         4성
7136305       818  174349490     전라     98    관광호텔업         4성
7162238       818  174349492     전라     98    관광호텔업         4성
7188248       843       1481     전라     59    관광호텔업         4성
7266393       843       2031     전라     59    관광호텔업         4성
7372144       843       2611     전라     59    관광호텔업         4성
7481165       843       2975     전라     59    관광호텔업         4성
7561826       843   15171206     전라     59    관광호텔업         4성
7634944       843   15171206     전라   59.0    관광호텔업         4성
7648979      1600   -5684392     전라    미분류      미분류        미등급
7654709      1600   -5682221     전라    미분류      미분류        미등급
7659265      1600    1040935     전라    미분류      미분류        미등급
7668470      1600    6713787     전라    미분류      미분류        미등급
7675241      1600    6713789     전라    미분류      미분류        미등급
7680367       531   31760941     제주  750.0  관광호텔_제주         5성
7700480       531   31760941     제주    750  관광호텔_제주         5성
7786554       531   35482131     제주    750  관광호텔_제주         5성
7895958       531   35482132     제주    750  관광호텔_제주         5성
8004269       531   35580397     제주    750  관광호텔_제주         5성
8112450       531   36987283     제주    750  관광호텔_제주         5성
8221332      1466      11588     제주    215  관광호텔_제주         5성
8254192      1466      12557     제주    215  관광호텔_제주         5성
8291685      1466      12790     제주    215  관광호텔_제주         5성
8325927      1466      12919     제주    215  관광호텔_제주         5성
8358280      1466      13014     제주    215  관광호텔_제주         5성
8390117      1652      19394     제주     44  가족호텔_제주         1성
8418531      1652      14887     제주     44  가족호텔_제주         1성
8456393      1652      14886     제주     44  가족호텔_제주         1성
8484624      1652      19395     제주     44  가족호텔_제주         1성
8499990      1652     202474     제주     44  가족호텔_제주         1성

In [37]:
df=df.drop(['region','객실수','업태구분명','hoteLgrade'], axis=1)
df

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,room_name,hotel_name,lead_time,scanned_date_time
0,1535,1040733,2022-01-01,2022-01-01 11:00:00,1,70000,-1 days +13:00:00,2022-01-01,GOODCHOICE,늦은 퇴실,창원명서동시카고,0,11:00:00
1,1535,1040733,2022-01-01,2022-01-01 23:00:00,1,60000,-1 days +01:00:00,2022-01-01,GOODCHOICE,늦은 퇴실,창원명서동시카고,0,23:00:00
2,1535,1040733,2022-01-02,2022-01-01 11:00:00,1,70000,0 days 13:00:00,2022-01-01,GOODCHOICE,늦은 퇴실,창원명서동시카고,1,11:00:00
3,1535,1040733,2022-01-02,2022-01-01 23:00:00,1,60000,0 days 01:00:00,2022-01-01,GOODCHOICE,늦은 퇴실,창원명서동시카고,1,23:00:00
4,1535,1040733,2022-01-02,2022-01-02 11:00:00,1,60000,-1 days +13:00:00,2022-01-02,GOODCHOICE,늦은 퇴실,창원명서동시카고,0,11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8529231,1652,202474,2023-10-23,2023-09-24 12:00:00,1,100000,28 days 12:00:00,2023-09-24,AGODA,패밀리 스위트 (Family Suite),중문리조트,29,12:00:00
8529232,1652,202474,2023-10-23,2023-09-25 17:00:00,1,100000,27 days 07:00:00,2023-09-25,AGODA,패밀리 스위트 (Family Suite),중문리조트,28,17:00:00
8529233,1652,202474,2023-10-23,2023-09-25 23:00:00,1,100000,27 days 01:00:00,2023-09-25,AGODA,패밀리 스위트 (Family Suite),중문리조트,28,23:00:00
8529234,1652,202474,2023-10-24,2023-09-25 17:00:00,1,100000,28 days 07:00:00,2023-09-25,AGODA,패밀리 스위트 (Family Suite),중문리조트,29,17:00:00
8529235,1652,202474,2023-10-24,2023-09-25 23:00:00,1,100000,28 days 01:00:00,2023-09-25,AGODA,패밀리 스위트 (Family Suite),중문리조트,29,23:00:00

In [43]:
def Create_end_time_df(df):
    # 본함수는 시간이 좀걸림 따로 하는게 좋음 
    
    # 그룹화하고 각 그룹별로 scanned_date의 가장 마지막 값을 선택
    result_df = df.groupby(['hotel_name','room_id', 'room_name', 'ota_type', 'booking_date', 'lead_time'], as_index=False)['scanned_date_time'].max()
    # 필터된 행만 inner join으로 남기기 
    filtered_df = pd.merge(df, result_df, on=['hotel_name', 'room_id', 'room_name', 'ota_type', 'booking_date', 'lead_time', 'scanned_date_time'])
    
    return filtered_df

In [44]:
filtered_df=Create_end_time_df(df)

In [45]:
filtered_df.head(3)

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,room_name,hotel_name,lead_time,scanned_date_time
0,1535,1040733,2022-01-01,2022-01-01 23:00:00,1,60000,-1 days +01:00:00,2022-01-01,GOODCHOICE,늦은 퇴실,창원명서동시카고,0,23:00:00
1,1535,1040733,2022-01-02,2022-01-01 23:00:00,1,60000,0 days 01:00:00,2022-01-01,GOODCHOICE,늦은 퇴실,창원명서동시카고,1,23:00:00
2,1535,1040733,2022-01-02,2022-01-02 23:00:00,1,60000,-1 days +01:00:00,2022-01-02,GOODCHOICE,늦은 퇴실,창원명서동시카고,0,23:00:00

In [50]:
filtered_df.hotel_id.nunique()

30

In [47]:
filtered_df.room_name.nunique()

131

In [48]:
filtered_df.room_id.nunique()

150

In [49]:
filtered_df.ota_type.nunique()

4

In [51]:
def create_instance_list(df):
    # 필요한 컬럼만 선택하여 고유한 조합을 포함하는 새 데이터프레임 생성
    selected_columns_df = df[['hotel_id','hotel_name', 'room_id', 'room_name', 'ota_type']].drop_duplicates()
    print("데이터세트 고유 호텔 갯수:", df.hotel_id.nunique())
    print("데이터세트 고유 룸 갯수:", df.room_id.nunique())
    print("데이터세트 OTA 갯수:", df.ota_type.nunique())
    print("데이터세트 OTA 목록:", df.ota_type.unique())
    # 선택된 컬럼들만 포함하는 딕셔너리의 리스트 생성
    instance = selected_columns_df.to_dict('records')
    
    return instance

In [280]:
# 데이터 범위 계산하기 -- 전체 공통 
def data_range_calculator(df):
    start_date =  df.booking_date.min()
    end_date=df.booking_date.max()
    print("데이터 시작날짜:", start_date)
    print("데이터 종료날짜:", end_date)
    # 시작 날짜와 종료 날짜 사이의 날짜 범위 생성
    date_range = pd.date_range(start=start_date, end=end_date)
    all_dates = date_range.strftime('%Y-%m-%d').tolist()
    # 날짜 범위의 길이 계산 (총 날짜 수)
    total_days = len(date_range)
    print("날짜 범위의 길이 :", total_days)
    
    # 리드타임 길이계산 
    lead_min=int(df.lead_time.min())
    lead_max=int(df.lead_time.max())
    print("리드타임 최소:", lead_min)
    print("리드타임 최대:", lead_max)
    ground_data_count = total_days * (lead_min+lead_max)
    print("해당범위 필요시계열 데이터갯수:", ground_data_count)
    
    return total_days,ground_data_count, start_date, end_date, all_dates

In [52]:
instance_list=create_instance_list(filtered_df)

데이터세트 고유 호텔 갯수: 30
데이터세트 고유 룸 갯수: 150
데이터세트 OTA 갯수: 4
데이터세트 OTA 목록: ['GOODCHOICE' 'BOOKING' 'AGODA' 'EXPEDIA']

In [281]:
total_days,ground_data_count,start_date, end_date,all_dates=data_range_calculator(filtered_df)
total_days

데이터 시작날짜: 2022-01-01
데이터 종료날짜: 2024-02-29
날짜 범위의 길이 : 790
리드타임 최소: 0
리드타임 최대: 30
해당범위 필요시계열 데이터갯수: 23700

790

In [125]:
def data_instance_validator(df,instance, ground_data_count):
    
    instance_df=df[df['room_id']==instance['room_id']]
    raw_data_all_count= instance_df.shape[0]
    data_coverage = (raw_data_all_count/ground_data_count)*100
    
    if data_coverage >= 70:
        instance['validated'] = "Y"
        instance['data_coverage'] = data_coverage
        
    else :
        instance['validated'] = "N"
        instance['data_coverage'] = data_coverage
    
    validate_instance_list.append(instance)
    
    return instance_df

In [171]:
def validate_instances(instance_list, df, ground_data_count):
    validate_instance_list = []
    
    for instance in instance_list:
        data_instance_validator(df, instance, ground_data_count)
        validate_instance_list.append(instance)
    
    validated_instance_list = pd.DataFrame(validate_instance_list)
    validated_instance_y = validated_instance_list.query("validated=='Y'")
    validate_instance_percentage = (validated_instance_y.shape[0] / len(validate_instance_list)) * 100
    
    print('유효 데이터갯수가 넘은 인스턴스 갯수:', validated_instance_y.shape[0])
    print('유효 인스턴스 갯수비율:', validate_instance_percentage)
    
    validated_instance_list_dicts = validated_instance_list.to_dict(orient='records')
    validated_instance_y=validated_instance_y.reset_index(drop=True)

    
    
    return validated_instance_list_dicts, validated_instance_y

In [248]:
validated_instance_list, validated_instance_y= validate_instances(instance_list,filtered_df,ground_data_count)

유효 데이터갯수가 넘은 인스턴스 갯수: 51
유효 인스턴스 갯수비율: 34.0

In [168]:
validated_df= filtered_df[filtered_df['room_id'].isin(validated_instance_y['room_id'])]
validated_df

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,room_name,hotel_name,lead_time,scanned_date_time
93199,1309,42032,2022-01-02,2022-01-01 23:00:00,1,507799,0 days 01:00:00,2022-01-01,BOOKING,이그제큐티브 킹 스위트룸,힐튼호텔경주,1,23:00:00
93200,1309,42032,2022-01-03,2022-01-01 23:00:00,1,471499,1 days 01:00:00,2022-01-01,BOOKING,이그제큐티브 킹 스위트룸,힐튼호텔경주,2,23:00:00
93201,1309,42032,2022-01-03,2022-01-02 23:00:00,1,471499,0 days 01:00:00,2022-01-02,BOOKING,이그제큐티브 킹 스위트룸,힐튼호텔경주,1,23:00:00
93202,1309,42032,2022-01-07,2022-01-01 23:00:00,1,500579,5 days 01:00:00,2022-01-01,BOOKING,이그제큐티브 킹 스위트룸,힐튼호텔경주,6,23:00:00
93203,1309,42032,2022-01-07,2022-01-02 23:00:00,1,500579,4 days 01:00:00,2022-01-02,BOOKING,이그제큐티브 킹 스위트룸,힐튼호텔경주,5,23:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1991996,1466,12557,2023-11-18,2023-10-23 23:00:00,1,350900,25 days 01:00:00,2023-10-23,AGODA,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,해비치호텔리조트,26,23:00:00
1991997,1466,12557,2023-11-19,2023-10-23 00:00:00,1,290400,27 days 00:00:00,2023-10-23,AGODA,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,해비치호텔리조트,28,00:00:00
1991998,1466,12557,2023-11-19,2023-10-23 23:00:00,1,290400,26 days 01:00:00,2023-10-23,AGODA,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,해비치호텔리조트,27,23:00:00
1991999,1466,12557,2023-11-20,2023-10-22 23:00:00,1,290400,28 days 01:00:00,2023-10-22,AGODA,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,해비치호텔리조트,29,23:00:00
1992000,1466,12557,2023-11-21,2023-10-22 23:00:00,1,290400,29 days 01:00:00,2023-10-22,AGODA,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,해비치호텔리조트,30,23:00:00

In [287]:
def get_missing_date(validated_instance_list, df,all_dates):
    
    updated_instances = [] 
    
    
    for instance in validated_instance_list:
        if instance['validated']== "Y":
            instance_df=df[df['room_id']==instance['room_id']]
            instance_all_booking_date = instance_df['booking_date'].unique().tolist()


            # 누락된 날짜 찾기
            missing_booking_dates = [date for date in all_dates if date not in instance_all_booking_date]

            instance['missing_date']=missing_booking_dates


        else :
            hotel_name = instance['hotel_name']
            room_name = instance['room_name']
            ota_type = instance['ota_type']
            print(f'{hotel_name}_{room_name}_{ota_type} 유효하지 않습니다')
            instance['missing_date'] = 'X'
        

        updated_instances.append(instance)
    

    return updated_instances

In [288]:
validated_instance_list_updated=get_missing_date(validated_instance_list, filtered_df,all_dates)

창원명서동시카고_늦은 퇴실_GOODCHOICE 유효하지 않습니다
창원명서동시카고_스위트(넷플릭스,조식,스타일러,공기청정기)_GOODCHOICE 유효하지 않습니다
창원명서동시카고_디럭스(넷플릭스,조식,스타일러,공기청정기)_GOODCHOICE 유효하지 않습니다
창원명서동시카고_빠른 입실_GOODCHOICE 유효하지 않습니다
창원명서동시카고_디럭스 트윈룸_BOOKING 유효하지 않습니다
힐튼호텔경주_이그제큐티브 킹 스위트 (King Executive Suite)_AGODA 유효하지 않습니다
힐튼호텔경주_에스페로 스위트 (Espero Suite)_AGODA 유효하지 않습니다
힐튼호텔경주_이그제큐티브 프리미엄 킹 스위트 (King Executive Premium Suite)_AGODA 유효하지 않습니다
힐튼호텔경주_이그제큐티브 레이크뷰 킹룸 (King Executive Lakeview)_AGODA 유효하지 않습니다
호텔브라운도트광안비치점_스탠다드(넷플릭스, PC, 욕조)_GOODCHOICE 유효하지 않습니다
호텔브라운도트광안비치점_디럭스(넷플릭스, PC, 욕조)_GOODCHOICE 유효하지 않습니다
호텔브라운도트광안비치점_테라스 프리미엄(넷플릭스, PC, 욕조 ,쇼파)_GOODCHOICE 유효하지 않습니다
호텔브라운도트광안비치점_트윈(넷플릭스, PC, 욕조)_GOODCHOICE 유효하지 않습니다
호텔브라운도트광안비치점_디럭스룸 (Deluxe )_AGODA 유효하지 않습니다
부산사상소르젠떼비지니스호텔_패밀리 스위트 (Family Suite)_AGODA 유효하지 않습니다
부산사상소르젠떼비지니스호텔_디럭스 킹룸 (Deluxe King Room)_AGODA 유효하지 않습니다
부산사상소르젠떼비지니스호텔_프리미엄룸 (Premium Room)_AGODA 유효하지 않습니다
부산사상소르젠떼비지니스호텔_프리미엄 트윈룸 (금연) (Premium Twin Room - Non-Smoking)_AGODA 유효하지 않습니다
부산사상소르젠떼비지니스호텔_스위트룸 (Suite Room)_AGODA 유효하지 않습니다
부산범일동브라운도트범일점부산역_스탠다드 더블룸_BOOKING 유효하지 않습니다
부산범일동브라운도트범일점부산역_디럭스 더블룸_BOOKING 유효하지 않습니다
부산범일동브라운도트범일점부산역_디럭스 킹룸_BOOKING 유효하지 않습니다
부산범일동브라운도트범일점부산역_디럭스 트윈룸_BOOKING 유효하지 않습니다
부산범일동브라운도트범일점부산역_패밀리 스위트룸_BOOKING 유효하지 않습니다
호메르스호텔_비즈니스 더블베드 (Business Double Bed)_AGODA 유효하지 않습니다
호메르스호텔_비즈니스 트윈룸 (BUSINESS TWIN BED ROOM)_AGODA 유효하지 않습니다
호메르스호텔_디럭스 트윈룸 - 오션뷰 (Deluxe Twin Room - Ocean view)_AGODA 유효하지 않습니다
호메르스호텔_하이 디럭스 더블 (High Deluxe Double)_AGODA 유효하지 않습니다
호메르스호텔_디럭스 더블 (오션뷰) (Deluxe Double - Ocean View)_AGODA 유효하지 않습니다
베스트루이스해밀턴호텔광안점_수페리어 킹룸 (Superior King Room)_AGODA 유효하지 않습니다
베스트루이스해밀턴호텔광안점_시크 스퀘어 트윈룸 (Chic Square Twin Room)_AGODA 유효하지 않습니다
베스트루이스해밀턴호텔광안점_Premium Half Ocean View Room_AGODA 유효하지 않습니다
베스트루이스해밀턴호텔광안점_디럭스 킹룸 (Deluxe King.)_AGODA 유효하지 않습니다
지앤지GG관광호텔부산대연동_스탠다드 더블(NETFLIX 무료 시청 가능)_GOODCHOICE 유효하지 않습니다
미포오션사이드호텔_수페리어 더블룸_BOOKING 유효하지 않습니다
미포오션사이드호텔_디럭스 더블룸 - 바다 전망_BOOKING 유효하지 않습니다
미포오션사이드호텔_특별한 혜택 - 디럭스 더블룸 - 바다 전망_BOOKING 유효하지 않습니다
미포오션사이드호텔_시티 더블 (City Double)_AGODA 유효하지 않습니다
베이하운드호텔_프리미어 패밀리룸 (Premier Family Room)_AGODA 유효하지 않습니다
파크하얏트부산_오션뷰 킹룸_BOOKING 유효하지 않습니다
파크하얏트부산_디럭스 킹룸_BOOKING 유효하지 않습니다
파크하얏트부산_킹룸_BOOKING 유효하지 않습니다
호텔라싸_디럭스룸 (Deluxe Room)_AGODA 유효하지 않습니다
호텔라싸_스탠다드룸 (Standard Room)_AGODA 유효하지 않습니다
호텔라싸_Suite (넷플릭스 시청가능)_GOODCHOICE 유효하지 않습니다
호텔라싸_Royal Suite (넷플릭스 시청가능)_GOODCHOICE 유효하지 않습니다
호텔라싸_Deluxe-연박가능 Early cheek-in (주차가능,n..._GOODCHOICE 유효하지 않습니다
신라스테이서초_스탠다드 더블룸_BOOKING 유효하지 않습니다
신라스테이서초_스탠다드 트윈룸_BOOKING 유효하지 않습니다
신라스테이서초_디럭스 더블룸_BOOKING 유효하지 않습니다
신라스테이서초_특별한 혜택 - 1인 여행객 패키지_BOOKING 유효하지 않습니다
신라스테이서초_프리미어 디럭스 더블룸 - 고층, 라운지 입장 포함, OTT TV 박스_BOOKING 유효하지 않습니다
목시서울인사동호텔_수페리어 트윈룸_BOOKING 유효하지 않습니다
더플라자서울오토그래프컬렉션_디럭스룸 (킹베드, 클럽 라운지 이용 포함) (Club Deluxe, Club lounge access, Guest room, 1 King)_AGODA 유효하지 않습니다
더플라자서울오토그래프컬렉션_디럭스룸, 킹사이즈침대 1개, 금연, 시내 전망_EXPEDIA 유효하지 않습니다
호텔케이월드_DELUXE DOUBLE_GOODCHOICE 유효하지 않습니다
신라스테이울산_프리미어 트윈룸 (Premier Twin Room)_AGODA 유효하지 않습니다
신라스테이울산_스탠다드 패밀리룸 (Standard Family Room)_AGODA 유효하지 않습니다
브라운도트호텔울산삼산_★특가★ 디럭스 더블(Netflix 시청 가능)_GOODCHOICE 유효하지 않습니다
브라운도트호텔울산삼산_슈페리어 더블(Netflix 시청 가능)_GOODCHOICE 유효하지 않습니다
브라운도트호텔울산삼산_디럭스 트윈(Netflix 시청 가능)_GOODCHOICE 유효하지 않습니다
브라운도트호텔울산삼산_레이트체크아웃_GOODCHOICE 유효하지 않습니다
브라운도트호텔울산삼산_그랜드 스위트(Netflix 시청 가능,스타일러)_GOODCHOICE 유효하지 않습니다
인천부평넘버25인천부평점_Deluxe couple P.C room (2PC, i5-10400,32인치 200Hz, GTX1660 6GB, 삼성16GB RAM, 사운드바, 넷플릭스)_GOODCHOICE 유효하지 않습니다
인천부평넘버25인천부평점_Standard room  _GOODCHOICE 유효하지 않습니다
인천부평넘버25인천부평점_Superior room_GOODCHOICE 유효하지 않습니다
인천부평넘버25인천부평점_Deluxe couple P.C room (2PC, i5-10400,32인..._GOODCHOICE 유효하지 않습니다
인천부평넘버25인천부평점_Relax (빠른입실-늦은퇴실)_GOODCHOICE 유효하지 않습니다
인천부평호텔주노_스탠다드(싱글PC I5-4670, GTX960, RAM16GB, 공기청정기, 욕조 및 금연실 랜덤배정))_GOODCHOICE 유효하지 않습니다
인천부평호텔주노_스위트커플PC룸(I5-8400&165Hz, GTX1060 6G, RAM16GB, 안마의자, 욕조(랜덤배정), 공기청정기, PC전용시스템테이블, 의자, 기계식키보드, G102)_GOODCHOICE 유효하지 않습니다
인천부평호텔주노_[도보전용]커플PC룸(I5-CPU&게이밍모니터, GTX1060, RAM16GB, 욕조랜덤배정, 공기청정기, PC전용시스템테이블, 의자, 기계식키보드, G102,좌석랜덤)_GOODCHOICE 유효하지 않습니다
인천부평호텔주노_커플PC룸(I5-CPU&게이밍모니터, GTX1060, RAM16GB, 욕조랜덤배정, 공기청정기, PC전용시스템테이블, 의자, 기계식키보드, G102,좌석랜덤)_GOODCHOICE 유효하지 않습니다
인천부평호텔주노_프리미엄커플PC(I5-8400&200Hz, GTX1060 6G, RAM16GB, 안마의자, 스타일러, 욕조,  공기청정기, PC전용시스템테이블, 의자, 기계식키보드, G102)_GOODCHOICE 유효하지 않습니다
쏠비치진도호텔_스탠다드 트윈룸 (Twin Standard)_AGODA 유효하지 않습니다
쏠비치진도호텔_호텔 슈페리어 오션뷰 패밀리 트윈룸 (키친 없음) (Hotel Superior Ocean View Family Twin Room without Kitchen)_AGODA 유효하지 않습니다
쏠비치진도호텔_리조트 스탠다드 스위트 (키친 없음) (Resort Standard Suite without Kitchen)_AGODA 유효하지 않습니다
쏠비치진도호텔_리조트 오션뷰 패밀리룸 (키친 없음) (Resort Ocean View Family Room without Kitchen)_AGODA 유효하지 않습니다
쏠비치진도호텔_리조트 부분 오션뷰 스위트 (키친) (Resort Partial Ocean View Suite with Kitchen)_AGODA 유효하지 않습니다
스위트호텔남원_디럭스 트리플룸_BOOKING 유효하지 않습니다
스위트호텔남원_디럭스 패밀리룸 (Deluxe Family Room)_AGODA 유효하지 않습니다
완주힐링_더 편한 방-복층(월풀욕조/슈퍼킹+슈퍼킹/넷플릭스무료시청)_GOODCHOICE 유효하지 않습니다
완주힐링_듀플렉스-패밀리 복층(넷플릭스무료/욕조/슈퍼킹+슈퍼킹)_GOODCHOICE 유효하지 않습니다
완주힐링_디럭스 - B.B.Q 패키지_GOODCHOICE 유효하지 않습니다
완주힐링_듀플렉스-오직 한 팀,패밀리 복층(넷플릭스무..._GOODCHOICE 유효하지 않습니다
완주힐링_듀플렉스-오직 한 팀,패밀리복층,B,.B.Q 패키..._GOODCHOICE 유효하지 않습니다
그랜드하얏트제주_트윈룸 - 도시 전망_BOOKING 유효하지 않습니다
그랜드하얏트제주_킹룸 - 바다 전망_BOOKING 유효하지 않습니다
그랜드하얏트제주_트윈룸 - 바다 전망_BOOKING 유효하지 않습니다
그랜드하얏트제주_코너 트윈 스위트룸_BOOKING 유효하지 않습니다
그랜드하얏트제주_킹룸 - 도시 전망_BOOKING 유효하지 않습니다
해비치호텔리조트_[호텔] 슈페리어 빌리지 트윈_GOODCHOICE 유효하지 않습니다
해비치호텔리조트_호텔 - 디럭스 씨사이드 트윈룸 (Hotel Deluxe Seaside Twin Room)_AGODA 유효하지 않습니다
해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 킹룸 (Hotel Superior Village View King Room)_AGODA 유효하지 않습니다
해비치호텔리조트_호텔 - 이그제큐티브 오션뷰 트윈룸 (Hotel Executive Ocean View Twin Room)_AGODA 유효하지 않습니다
중문리조트_패밀리 스위트룸_BOOKING 유효하지 않습니다
중문리조트_패밀리 스위트_GOODCHOICE 유효하지 않습니다
중문리조트_주니어 스위트_GOODCHOICE 유효하지 않습니다
중문리조트_주니어 스위트룸_BOOKING 유효하지 않습니다
중문리조트_패밀리 스위트 (Family Suite)_AGODA 유효하지 않습니다

In [293]:
validated_instance_df=pd.DataFrame(validated_instance_list_updated).query('validated=="Y"')
validated_instance_df

,hotel_id,hotel_name,room_id,room_name,ota_type,validated,data_coverage,missing_date
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,"[2022-01-01, 2022-01-04, 2022-01-05, 2022-01-0..."
31,257,베스트루이스해밀턴호텔광안점,6133,1베드룸 스위트 (One-Bedroom Suite),AGODA,Y,71,"[2022-01-01, 2022-01-07, 2022-01-08, 2022-01-1..."
35,139,아바니센트럴부산,41928,디럭스 트윈룸 - 산 전망,BOOKING,Y,90,"[2022-10-24, 2022-10-25, 2022-10-26, 2023-06-1..."
36,139,아바니센트럴부산,41929,디럭스 트윈룸 - 도시 전망,BOOKING,Y,91,"[2022-10-24, 2022-10-25, 2022-10-26, 2023-06-12]"
37,139,아바니센트럴부산,41930,프리미어 더블룸,BOOKING,Y,95,[]
38,139,아바니센트럴부산,41931,주니어 스위트룸,BOOKING,Y,97,[]
39,139,아바니센트럴부산,41932,스위트룸,BOOKING,Y,97,[]
41,271,지앤지GG관광호텔부산대연동,1037316,디럭스 커플(NETFLIX 무료 시청 가능),GOODCHOICE,Y,72,"[2022-07-03, 2022-07-04, 2022-07-05, 2022-07-0..."
42,271,지앤지GG관광호텔부산대연동,1037318,프리미엄 코리안(NETFLIX 무료 시청 가능),GOODCHOICE,Y,78,"[2023-01-07, 2023-01-14, 2023-01-21, 2023-01-2..."
43,271,지앤지GG관광호텔부산대연동,1037321,스카이(NETFLIX 무료 시청 가능),GOODCHOICE,Y,79,"[2023-12-10, 2023-12-11, 2023-12-12, 2023-12-1..."
44,271,지앤지GG관광호텔부산대연동,1037350,디럭스 트윈(NETFLIX 무료 시청 가능),GOODCHOICE,Y,80,"[2023-12-10, 2023-12-11, 2023-12-12, 2023-12-1..."
48,312,미포오션사이드호텔,9131,오션 더블 (Ocean Double),AGODA,Y,74,"[2022-02-07, 2022-06-03, 2023-10-07, 2023-10-0..."
50,269,베이하운드호텔,13000,스탠다드 트윈 (Standard Twin),AGODA,Y,79,"[2023-03-29, 2023-04-02, 2023-04-03, 2023-04-0..."
51,269,베이하운드호텔,13001,스탠다드 더블 (Standard Double),AGODA,Y,90,[]
52,269,베이하운드호텔,13004,디럭스 더블 (Deluxe Double),AGODA,Y,93,"[2022-01-01, 2022-04-28, 2023-12-23]"
53,269,베이하운드호텔,13005,디럭스 트리플 (Deluxe Triple),AGODA,Y,80,"[2022-01-01, 2023-04-02, 2023-04-15, 2023-06-3..."
55,302,파크하얏트부산,45332,패밀리 스위트룸,BOOKING,Y,91,"[2022-01-01, 2022-06-04, 2022-06-05, 2022-06-3..."
56,302,파크하얏트부산,45333,이그제큐티브 패밀리 스위트룸,BOOKING,Y,75,"[2022-01-01, 2022-01-03, 2022-01-05, 2022-01-0..."
70,351,목시서울인사동호텔,11251,슈페리어 트윈 (주차불가),GOODCHOICE,Y,80,"[2022-12-24, 2023-10-01, 2023-10-06, 2023-10-0..."
71,351,목시서울인사동호텔,12176,"스탠다드룸 (싱글베드 2개) (Standard Twin, Guest room, 2 ...",AGODA,Y,87,[]
72,351,목시서울인사동호텔,12177,"슈페리어 시티뷰 룸 (싱글베드 2개) (Superior Twin, Guest roo...",AGODA,Y,87,[]
73,351,목시서울인사동호텔,12178,"슈페리어 시티뷰 룸 (더블베드) (Superior Double, Guest room...",AGODA,Y,87,[]
75,1378,L7강남,7855,스탠다드 더블 (Standard Double),AGODA,Y,98,[]
76,1378,L7강남,9461,스탠다드 트윈룸,BOOKING,Y,94,[2023-07-17]
77,1378,L7강남,9462,스탠다드 더블룸,BOOKING,Y,96,[]
78,1378,L7강남,9469,수페리어 더블룸,BOOKING,Y,95,[]
79,1378,L7강남,9470,수페리어 트윈룸,BOOKING,Y,95,[]
80,1387,호텔인나인,7558,스탠다드 더블룸,BOOKING,Y,97,[]
81,1387,호텔인나인,7559,스탠다드 트윈룸,BOOKING,Y,95,[]
82,1387,호텔인나인,7560,디럭스 더블 코너룸,BOOKING,Y,92,"[2022-01-01, 2022-12-24, 2022-12-31]"
83,1387,호텔인나인,7561,주니어 스위트룸,BOOKING,Y,96,"[2022-01-01, 2022-12-24]"
84,1387,호텔인나인,8846,"디럭스 더블룸 - 목재 바닥, 3층에 위치",BOOKING,Y,91,"[2022-01-01, 2022-12-24]"
85,1367,호텔페이토삼성,8498,디럭스 더블 (Deluxe Double),AGODA,Y,88,"[2023-10-07, 2023-10-18, 2023-12-24]"
86,1367,호텔페이토삼성,8499,디럭스 트윈 (Deluxe Twin),AGODA,Y,76,"[2022-06-04, 2022-07-21, 2023-10-07, 2023-10-1..."
87,1367,호텔페이토삼성,42149,디럭스 더블룸,BOOKING,Y,79,"[2022-08-14, 2023-10-07, 2023-10-15, 2023-10-1..."
88,1367,호텔페이토삼성,8500,어반룸 (Urban Room),AGODA,Y,87,"[2022-01-01, 2023-10-07, 2023-10-14, 2023-10-1..."
89,1367,호텔페이토삼성,42224,어번 더블룸,BOOKING,Y,79,"[2022-01-01, 2023-08-05, 2023-10-07, 2023-10-1..."
90,143,더플라자서울오토그래프컬렉션,33178,"디럭스룸 (싱글베드 2개) (Deluxe Twin, Guest room, 2 Twi...",AGODA,Y,74,"[2022-12-24, 2023-04-29, 2023-05-05, 2023-09-0..."
91,143,더플라자서울오토그래프컬렉션,33179,"디럭스룸 (킹베드) (Deluxe, Guest room, 1 King)",AGODA,Y,74,"[2022-12-24, 2023-09-07, 2023-10-07, 2023-10-1..."
93,143,더플라자서울오토그래프컬렉션,45039,프리미어 스위트룸,BOOKING,Y,71,"[2022-01-01, 2022-01-08, 2022-11-19, 2022-12-0..."
96,980,호텔케이월드,1040337,DELUXE TWIN,GOODCHOICE,Y,71,"[2023-10-03, 2023-10-04, 2023-10-05, 2023-10-0..."
97,980,호텔케이월드,1040339,PREMIUM DOUBLE,GOODCHOICE,Y,78,[]
98,980,호텔케이월드,1040340,PREMIUM TWIN,GOODCHOICE,Y,77,[]
99,980,호텔케이월드,1040342,SUITE,GOODCHOICE,Y,78,[]
100,217,신라스테이울산,8256,스탠다드 더블 베드룸 (Standard Double Bed Room),AGODA,Y,82,"[2022-10-06, 2022-10-07, 2022-10-08, 2022-10-0..."
101,217,신라스테이울산,8260,디럭스 더블 베드룸 (Deluxe Double Bed Room),AGODA,Y,88,"[2022-10-06, 2022-10-07, 2022-10-08, 2022-10-0..."
103,217,신라스테이울산,8264,프리미어 더블룸 (Premier Double Room),AGODA,Y,81,"[2022-01-06, 2022-01-07, 2022-01-08, 2022-01-0..."
126,843,스위트호텔남원,2031,디럭스 트리플룸 (Deluxe Triple Room),AGODA,Y,74,"[2022-01-01, 2022-01-06, 2022-05-05, 2022-05-1..."
127,843,스위트호텔남원,2611,디럭스 트윈룸 (Deluxe Twin Room),AGODA,Y,77,"[2022-01-01, 2022-01-06, 2022-05-05, 2022-05-1..."
128,843,스위트호텔남원,2975,디럭스 트윈룸,BOOKING,Y,72,"[2022-01-01, 2022-01-06, 2022-05-05, 2022-05-1..."
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,"[2022-03-16, 2022-05-19, 2022-05-26, 2022-05-2..."

In [294]:
# missing_date 컬럼을 이용하여 각 날짜를 별도의 행으로 확장
df_exploded = validated_instance_df.explode('missing_date')

# hotel_name과 room_name을 결합하여 식별자 생성
df_exploded['identifier'] = df_exploded['hotel_name'] + "_" + df_exploded['room_name']
df_exploded

,hotel_id,hotel_name,room_id,room_name,ota_type,validated,data_coverage,missing_date,identifier
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-01,힐튼호텔경주_이그제큐티브 킹 스위트룸
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-04,힐튼호텔경주_이그제큐티브 킹 스위트룸
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-05,힐튼호텔경주_이그제큐티브 킹 스위트룸
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-06,힐튼호텔경주_이그제큐티브 킹 스위트룸
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-05-05,힐튼호텔경주_이그제큐티브 킹 스위트룸
...,...,...,...,...,...,...,...,...,...
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-25,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-26,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-27,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-28,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-29,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...

In [ ]:
import matplotlib.dates as mdates
# 식별자별로 서브플롯 생성
identifiers = df_exploded['identifier'].unique()
n_identifiers = len(identifiers)

fig, axs = plt.subplots(n_identifiers, 1, figsize=(10, n_identifiers * 3), sharex=True)

for i, identifier in enumerate(identifiers):
    ax = axs[i]
    temp_df = df_exploded[df_exploded['identifier'] == identifier]
    ax.plot(temp_df['missing_date'], [identifier] * len(temp_df), 'o', label=identifier)
    ax.set_title(identifier)
    ax.xaxis.set_major_locator(mdates.MonthLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
    ax.set_ylabel('누락된 날짜')
    # y축 레이블 간소화
    ax.set_yticks([])

plt.gcf().autofmt_xdate()  # 날짜 레이블이 겹치지 않도록 자동으로 조정
plt.tight_layout()
plt.show()

In [300]:
# 'missing_date'를 datetime으로 변환
df_exploded['missing_date'] = pd.to_datetime(df_exploded['missing_date'])

# identifier 별로 그룹화하고, 각 그룹 내에서 연속된 날짜의 최대 길이를 계산하는 함수를 적용
def check_consecutive_dates(group):
    # missing_date를 정렬
    sorted_dates = group.sort_values()
    
    # 연속된 날짜의 길이 계산
    deltas = sorted_dates.diff().dt.days == 1
    consecutive_lengths = deltas.groupby((deltas == False).cumsum()).cumsum()
    
    # 7일 이상 연속되는 경우가 있는지 확인
    return 'N' if any(consecutive_lengths >= 7) else 'Y'

# 'consecutive' 칼럼에 각 identifier 별로 연속된 날짜의 조건을 충족하는지 여부를 표시
df_exploded['consecutive'] = df_exploded.groupby('identifier')['missing_date'].transform(check_consecutive_dates)
df_exploded

,hotel_id,hotel_name,room_id,room_name,ota_type,validated,data_coverage,missing_date,identifier,consecutive
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-01,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-04,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-05,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-06,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-05-05,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
...,...,...,...,...,...,...,...,...,...,...
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-25,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-26,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-27,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-28,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-29,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N

In [308]:
df_exploded

,hotel_id,hotel_name,room_id,room_name,ota_type,validated,data_coverage,missing_date,identifier,consecutive
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-01,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-04,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-05,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-01-06,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
8,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,2022-05-05,힐튼호텔경주_이그제큐티브 킹 스위트룸,Y
...,...,...,...,...,...,...,...,...,...,...
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-25,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-26,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-27,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-28,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N
141,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,2024-02-29,해비치호텔리조트_호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Vi...,N

In [312]:
validated_instance_df=pd.merge(validated_instance_df,df_exploded[['room_id','consecutive']].drop_duplicates(), how='left', on='room_id')

In [313]:
validated_instance_df

,hotel_id,hotel_name,room_id,room_name,ota_type,validated,data_coverage,missing_date,consecutive
0,1309,힐튼호텔경주,42032,이그제큐티브 킹 스위트룸,BOOKING,Y,92,"[2022-01-01, 2022-01-04, 2022-01-05, 2022-01-0...",Y
1,257,베스트루이스해밀턴호텔광안점,6133,1베드룸 스위트 (One-Bedroom Suite),AGODA,Y,71,"[2022-01-01, 2022-01-07, 2022-01-08, 2022-01-1...",Y
2,139,아바니센트럴부산,41928,디럭스 트윈룸 - 산 전망,BOOKING,Y,90,"[2022-10-24, 2022-10-25, 2022-10-26, 2023-06-1...",Y
3,139,아바니센트럴부산,41929,디럭스 트윈룸 - 도시 전망,BOOKING,Y,91,"[2022-10-24, 2022-10-25, 2022-10-26, 2023-06-12]",Y
4,139,아바니센트럴부산,41930,프리미어 더블룸,BOOKING,Y,95,[],Y
5,139,아바니센트럴부산,41931,주니어 스위트룸,BOOKING,Y,97,[],Y
6,139,아바니센트럴부산,41932,스위트룸,BOOKING,Y,97,[],Y
7,271,지앤지GG관광호텔부산대연동,1037316,디럭스 커플(NETFLIX 무료 시청 가능),GOODCHOICE,Y,72,"[2022-07-03, 2022-07-04, 2022-07-05, 2022-07-0...",N
8,271,지앤지GG관광호텔부산대연동,1037318,프리미엄 코리안(NETFLIX 무료 시청 가능),GOODCHOICE,Y,78,"[2023-01-07, 2023-01-14, 2023-01-21, 2023-01-2...",N
9,271,지앤지GG관광호텔부산대연동,1037321,스카이(NETFLIX 무료 시청 가능),GOODCHOICE,Y,79,"[2023-12-10, 2023-12-11, 2023-12-12, 2023-12-1...",N
10,271,지앤지GG관광호텔부산대연동,1037350,디럭스 트윈(NETFLIX 무료 시청 가능),GOODCHOICE,Y,80,"[2023-12-10, 2023-12-11, 2023-12-12, 2023-12-1...",N
11,312,미포오션사이드호텔,9131,오션 더블 (Ocean Double),AGODA,Y,74,"[2022-02-07, 2022-06-03, 2023-10-07, 2023-10-0...",Y
12,269,베이하운드호텔,13000,스탠다드 트윈 (Standard Twin),AGODA,Y,79,"[2023-03-29, 2023-04-02, 2023-04-03, 2023-04-0...",Y
13,269,베이하운드호텔,13001,스탠다드 더블 (Standard Double),AGODA,Y,90,[],Y
14,269,베이하운드호텔,13004,디럭스 더블 (Deluxe Double),AGODA,Y,93,"[2022-01-01, 2022-04-28, 2023-12-23]",Y
15,269,베이하운드호텔,13005,디럭스 트리플 (Deluxe Triple),AGODA,Y,80,"[2022-01-01, 2023-04-02, 2023-04-15, 2023-06-3...",Y
16,302,파크하얏트부산,45332,패밀리 스위트룸,BOOKING,Y,91,"[2022-01-01, 2022-06-04, 2022-06-05, 2022-06-3...",Y
17,302,파크하얏트부산,45333,이그제큐티브 패밀리 스위트룸,BOOKING,Y,75,"[2022-01-01, 2022-01-03, 2022-01-05, 2022-01-0...",Y
18,351,목시서울인사동호텔,11251,슈페리어 트윈 (주차불가),GOODCHOICE,Y,80,"[2022-12-24, 2023-10-01, 2023-10-06, 2023-10-0...",Y
19,351,목시서울인사동호텔,12176,"스탠다드룸 (싱글베드 2개) (Standard Twin, Guest room, 2 ...",AGODA,Y,87,[],Y
20,351,목시서울인사동호텔,12177,"슈페리어 시티뷰 룸 (싱글베드 2개) (Superior Twin, Guest roo...",AGODA,Y,87,[],Y
21,351,목시서울인사동호텔,12178,"슈페리어 시티뷰 룸 (더블베드) (Superior Double, Guest room...",AGODA,Y,87,[],Y
22,1378,L7강남,7855,스탠다드 더블 (Standard Double),AGODA,Y,98,[],Y
23,1378,L7강남,9461,스탠다드 트윈룸,BOOKING,Y,94,[2023-07-17],Y
24,1378,L7강남,9462,스탠다드 더블룸,BOOKING,Y,96,[],Y
25,1378,L7강남,9469,수페리어 더블룸,BOOKING,Y,95,[],Y
26,1378,L7강남,9470,수페리어 트윈룸,BOOKING,Y,95,[],Y
27,1387,호텔인나인,7558,스탠다드 더블룸,BOOKING,Y,97,[],Y
28,1387,호텔인나인,7559,스탠다드 트윈룸,BOOKING,Y,95,[],Y
29,1387,호텔인나인,7560,디럭스 더블 코너룸,BOOKING,Y,92,"[2022-01-01, 2022-12-24, 2022-12-31]",Y
30,1387,호텔인나인,7561,주니어 스위트룸,BOOKING,Y,96,"[2022-01-01, 2022-12-24]",Y
31,1387,호텔인나인,8846,"디럭스 더블룸 - 목재 바닥, 3층에 위치",BOOKING,Y,91,"[2022-01-01, 2022-12-24]",Y
32,1367,호텔페이토삼성,8498,디럭스 더블 (Deluxe Double),AGODA,Y,88,"[2023-10-07, 2023-10-18, 2023-12-24]",Y
33,1367,호텔페이토삼성,8499,디럭스 트윈 (Deluxe Twin),AGODA,Y,76,"[2022-06-04, 2022-07-21, 2023-10-07, 2023-10-1...",Y
34,1367,호텔페이토삼성,42149,디럭스 더블룸,BOOKING,Y,79,"[2022-08-14, 2023-10-07, 2023-10-15, 2023-10-1...",Y
35,1367,호텔페이토삼성,8500,어반룸 (Urban Room),AGODA,Y,87,"[2022-01-01, 2023-10-07, 2023-10-14, 2023-10-1...",Y
36,1367,호텔페이토삼성,42224,어번 더블룸,BOOKING,Y,79,"[2022-01-01, 2023-08-05, 2023-10-07, 2023-10-1...",Y
37,143,더플라자서울오토그래프컬렉션,33178,"디럭스룸 (싱글베드 2개) (Deluxe Twin, Guest room, 2 Twi...",AGODA,Y,74,"[2022-12-24, 2023-04-29, 2023-05-05, 2023-09-0...",N
38,143,더플라자서울오토그래프컬렉션,33179,"디럭스룸 (킹베드) (Deluxe, Guest room, 1 King)",AGODA,Y,74,"[2022-12-24, 2023-09-07, 2023-10-07, 2023-10-1...",N
39,143,더플라자서울오토그래프컬렉션,45039,프리미어 스위트룸,BOOKING,Y,71,"[2022-01-01, 2022-01-08, 2022-11-19, 2022-12-0...",N
40,980,호텔케이월드,1040337,DELUXE TWIN,GOODCHOICE,Y,71,"[2023-10-03, 2023-10-04, 2023-10-05, 2023-10-0...",Y
41,980,호텔케이월드,1040339,PREMIUM DOUBLE,GOODCHOICE,Y,78,[],Y
42,980,호텔케이월드,1040340,PREMIUM TWIN,GOODCHOICE,Y,77,[],Y
43,980,호텔케이월드,1040342,SUITE,GOODCHOICE,Y,78,[],Y
44,217,신라스테이울산,8256,스탠다드 더블 베드룸 (Standard Double Bed Room),AGODA,Y,82,"[2022-10-06, 2022-10-07, 2022-10-08, 2022-10-0...",Y
45,217,신라스테이울산,8260,디럭스 더블 베드룸 (Deluxe Double Bed Room),AGODA,Y,88,"[2022-10-06, 2022-10-07, 2022-10-08, 2022-10-0...",Y
46,217,신라스테이울산,8264,프리미어 더블룸 (Premier Double Room),AGODA,Y,81,"[2022-01-06, 2022-01-07, 2022-01-08, 2022-01-0...",N
47,843,스위트호텔남원,2031,디럭스 트리플룸 (Deluxe Triple Room),AGODA,Y,74,"[2022-01-01, 2022-01-06, 2022-05-05, 2022-05-1...",Y
48,843,스위트호텔남원,2611,디럭스 트윈룸 (Deluxe Twin Room),AGODA,Y,77,"[2022-01-01, 2022-01-06, 2022-05-05, 2022-05-1...",Y
49,843,스위트호텔남원,2975,디럭스 트윈룸,BOOKING,Y,72,"[2022-01-01, 2022-01-06, 2022-05-05, 2022-05-1...",Y
50,1466,해비치호텔리조트,12557,호텔 - 슈페리어 빌리지뷰 트윈룸 (Hotel Superior Village Vie...,AGODA,Y,71,"[2022-03-16, 2022-05-19, 2022-05-26, 2022-05-2...",N

In [315]:
room_id_list=[41928,41929,41930,41931,41932]

In [319]:
abani=filtered_df[filtered_df['room_id'].isin(room_id_list)]
abani

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,room_name,hotel_name,lead_time,scanned_date_time
432001,139,41928,2022-01-01,2022-01-01 23:00:00,1,188100,-1 days +01:00:00,2022-01-01,BOOKING,디럭스 트윈룸 - 산 전망,아바니센트럴부산,0,23:00:00
432002,139,41928,2022-01-02,2022-01-01 23:00:00,1,130680,0 days 01:00:00,2022-01-01,BOOKING,디럭스 트윈룸 - 산 전망,아바니센트럴부산,1,23:00:00
432003,139,41928,2022-01-02,2022-01-02 23:00:00,1,143704,-1 days +01:00:00,2022-01-02,BOOKING,디럭스 트윈룸 - 산 전망,아바니센트럴부산,0,23:00:00
432004,139,41928,2022-01-03,2022-01-01 23:00:00,1,130680,1 days 01:00:00,2022-01-01,BOOKING,디럭스 트윈룸 - 산 전망,아바니센트럴부산,2,23:00:00
432005,139,41928,2022-01-03,2022-01-02 23:00:00,1,148390,0 days 01:00:00,2022-01-02,BOOKING,디럭스 트윈룸 - 산 전망,아바니센트럴부산,1,23:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
543533,139,41932,2024-02-29,2024-02-25 23:00:00,0,286000,3 days 01:00:00,2024-02-25,BOOKING,스위트룸,아바니센트럴부산,4,23:00:00
543534,139,41932,2024-02-29,2024-02-26 23:00:00,1,286000,2 days 01:00:00,2024-02-26,BOOKING,스위트룸,아바니센트럴부산,3,23:00:00
543535,139,41932,2024-02-29,2024-02-27 23:00:00,1,286000,1 days 01:00:00,2024-02-27,BOOKING,스위트룸,아바니센트럴부산,2,23:00:00
543536,139,41932,2024-02-29,2024-02-28 23:00:00,1,286000,0 days 01:00:00,2024-02-28,BOOKING,스위트룸,아바니센트럴부산,1,23:00:00
543537,139,41932,2024-02-29,2024-02-29 23:00:00,1,286000,-1 days +01:00:00,2024-02-29,BOOKING,스위트룸,아바니센트럴부산,0,23:00:00

In [320]:
holiday=pd.read_csv("holiday_calender_2022_2024.csv")

In [321]:
holiday

            date day_of_week dateName high_demand
0     2022-01-01    Saturday     1월1일           Y
1     2022-01-02      Sunday        N           N
2     2022-01-03      Monday        N           N
3     2022-01-04     Tuesday        N           N
4     2022-01-05   Wednesday        N           N
...          ...         ...      ...         ...
1091  2024-12-27      Friday        N           Y
1092  2024-12-28    Saturday        N           Y
1093  2024-12-29      Sunday        N           N
1094  2024-12-30      Monday        N           N
1095  2024-12-31     Tuesday        N           N

[1096 rows x 4 columns]

In [323]:
abani=pd.merge(abani,holiday[['date','high_demand','day_of_week']], how='inner', left_on='booking_date', right_on='date')
abani

,hotel_id,room_id,booking_date,scanned_date,remain,price,date_diff,scanned_date_date,ota_type,room_name,hotel_name,lead_time,scanned_date_time,date,high_demand,day_of_week
0,139,41928,2022-01-01,2022-01-01 23:00:00,1,188100,-1 days +01:00:00,2022-01-01,BOOKING,디럭스 트윈룸 - 산 전망,아바니센트럴부산,0,23:00:00,2022-01-01,Y,Saturday
1,139,41929,2022-01-01,2022-01-01 23:00:00,1,188100,-1 days +01:00:00,2022-01-01,BOOKING,디럭스 트윈룸 - 도시 전망,아바니센트럴부산,0,23:00:00,2022-01-01,Y,Saturday
2,139,41930,2022-01-01,2022-01-01 23:00:00,1,227700,-1 days +01:00:00,2022-01-01,BOOKING,프리미어 더블룸,아바니센트럴부산,0,23:00:00,2022-01-01,Y,Saturday
3,139,41931,2022-01-01,2022-01-01 23:00:00,1,247500,-1 days +01:00:00,2022-01-01,BOOKING,주니어 스위트룸,아바니센트럴부산,0,23:00:00,2022-01-01,Y,Saturday
4,139,41932,2022-01-01,2022-01-01 23:00:00,1,277200,-1 days +01:00:00,2022-01-01,BOOKING,스위트룸,아바니센트럴부산,0,23:00:00,2022-01-01,Y,Saturday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111532,139,41932,2023-06-12,2023-06-08 23:00:00,1,341000,3 days 01:00:00,2023-06-08,BOOKING,스위트룸,아바니센트럴부산,4,23:00:00,2023-06-12,N,Monday
111533,139,41932,2023-06-12,2023-06-09 23:00:00,1,341000,2 days 01:00:00,2023-06-09,BOOKING,스위트룸,아바니센트럴부산,3,23:00:00,2023-06-12,N,Monday
111534,139,41932,2023-06-12,2023-06-10 23:00:00,1,341000,1 days 01:00:00,2023-06-10,BOOKING,스위트룸,아바니센트럴부산,2,23:00:00,2023-06-12,N,Monday
111535,139,41932,2023-06-12,2023-06-11 23:00:00,1,341000,0 days 01:00:00,2023-06-11,BOOKING,스위트룸,아바니센트럴부산,1,23:00:00,2023-06-12,N,Monday
111536,139,41932,2023-06-12,2023-06-12 23:00:00,1,341000,-1 days +01:00:00,2023-06-12,BOOKING,스위트룸,아바니센트럴부산,0,23:00:00,2023-06-12,N,Monday

In [324]:
abani.to_csv("abani.csv", encoding='utf-8-sig', index=False)